axboe/liburing

- src/include/liburing.h
- test/send_recvmsg.c
> liburing: add io_uring_prep_{recv,send}msg

- src/include/liburing.h
- test/Makefile
- test/sq-space_left.c
New function to calculate how much space you have left in the submission queue.
> New function io_uring_sq_space_left

- examples/ucontext-cp.c
also add add timeout to indicate that different coroutines run in parallel actually
```shell
$ ./ucontext-cp io_uring-cp.c io_uring-cp.c.1 io_uring-test.c io_uring-test.c1 link-cp.c link-cp.c1
copying 3 files...
4->5: readv 1024 bytes from 0
6->7: readv 1024 bytes from 0
8->9: readv 1024 bytes from 0
4->5: writev 1024 bytes from 0
6->7: writev 1024 bytes from 0
8->9: writev 1024 bytes from 0
4->5: wait 1 second(s)
8->9: wait 1 second(s)
6->7: wait 1 second(s)
4->5: readv 1024 bytes from 1024
8->9: readv 1024 bytes from 1024
6->7: readv 1024 bytes from 1024
4->5: writev 1024 bytes from 1024
8->9: writev 1024 bytes from 1024
6->7: writev 785 bytes from 1024
4->5: wait 1 second(s)
8->9: wait 1 second(s)
6->7: done with ret code 0
4->5: readv 1024 bytes from 2048
8->9: readv 1024 bytes from …
```
> examples/ucontext-cp: more complex example to show how ucontext works with io_uring

- .gitignore
- src/include/liburing.h
- src/queue.c
- test/Makefile
- test/cq-peek-batch.c
- test/cq-ready.c
Added new two new function
* io_uring_cq_ready(), returns the about of completion queue entries ready.
* io_uring_peek_batch_cqe(), get a batch of completion queue entries.
> New functions

- man/io_uring_setup.2
- src/include/liburing/io_uring.h
> io_uring.h: add IORING_FEAT_RW_CUR_POS flag

- man/io_uring_enter.2
> io_uring_enter.2: document IOSQE_IO_HARDLINK

- test/statx.c
dummy patch, I forgot to push it in my previous merge request
> test: fix statx comment

- .gitignore
- test/Makefile
- test/across-fork.c
Signed-off-by: Andres Freund <andres@anarazel.de>
> Add test for sharing uring across fork

- .gitignore
- test/accept-link.c
- test/connect.c
- test/fadvise.c
- test/madvise.c
- test/poll-v-poll.c
- test/read-write.c
- test/send_recv.c
- test/send_recvmsg.c
- test/short-read.c
This includes cleanups and fixes for issues on kernels that do not support io_uring fully,
> Test suite improvements

- src/include/liburing.h
> liburing.h: add const type qualifier

- README
Ok, missed this one when preparing the other changes. :/
[ BTW, any plan to cut a release? I'd like to upload these changes coming from an official tarball, instead of creating a snapshot from git master. :) ]
> README: Update license information

- src/include/liburing.h
- src/liburing.map
- src/register.c
A new handy utility function for IORING_REGISTER_EVENTFD_ASYNC OP
Signed-off-by: Mark Papadakis <markpapadakis@gmail.com>
> Utility function io_uring_register_eventfd_async

- man/io_uring_enter.2
Adding IORING_OP_OPENAT2 description to the man page.
> Adding section describing IORING_OP_OPENAT2

- man/io_uring_enter.2
Add details of the splice operation to the man page.
> Adding description for the IORING_OP_SPLICE operation

- man/io_uring_enter.2
IORING_OP_EPOLL_CTL description added to man page.
> Adding section to describe IORING_OP_EPOLL_CTL

- man/io_uring_setup.2
Signed-off-by: Xuanyi Fu <xfu11@jhu.edu>
> man/io_uring_setup.2: document IORING_SETUP_CLAMP

- src/include/liburing.h
Without the memory barrier, we could miss an update and think the SQ
wasn't ready when in fact it was.
> Fix io_uring_sq_ready() to use load acquire to read khead

- man/io_uring.7
Draft version of the section 7 man page for io_uring.
> Adding section 7 man page for io_uring

- src/include/liburing.h
> liburing.h: add `io_uring_prep_tee`

- man/io_uring.7
Adding full example to io_uring(7) man page while also fixing some text to comply to the "semantic new lines" recommendation from man-pages(7).
> Adding full example

- debian/liburing-dev.manpages
- man/io_uring_get_sqe.3
- man/io_uring_queue_exit.3
- man/io_uring_queue_init.3
I also updated the other two from the previous PR to use the most recent release tag and changed the date to the date of the release.
https://github.com/axboe/liburing/issues/190
> Add man page for io_uring_get_sqe

- man/io_uring_setup.2
Signed-off-by: Sergei Iashin <s_yashin@head-point.ru>
> man/io_uring_setup.2: a version of IORING_FEAT_SQPOLL_NONFIXED feature availability has been changed to 5.11

- man/io_uring_setup.2
Not much to it. That confused me a bit my first read through.
> Fixed typo in manpage

- Makefile
- liburing.spec
Noticed I couldn't see `man 7 io_uring` working, saw https://github.com/axboe/liburing/pull/251 but since the guy hasn't responded yet, just made this PR quickly.
> Install man7 pages

- src/include/liburing.h
As discussed in #299. If anything needs changing feel free to say. Compile successfully.
Thanks,
James.
> Added prep function for sync_file_range op

- test/500f9fbadef8-test.c
- test/accept.c
- test/cq-overflow.c
- test/d4ae271dfaae-test.c
- test/fadvise.c
- test/file-register.c
- test/file-update.c
- test/fsync.c
- test/helpers.c
- test/helpers.h
- test/io-cancel.c
- test/iopoll.c
- test/madvise.c
- test/open-close.c
- test/openat2.c
- test/probe.c
- test/read-write.c
- test/short-read.c
- test/splice.c
- test/sq-poll-dup.c
- test/sq-poll-share.c
- test/statx.c
- test/stdout.c
- test/submit-reuse.c
- test/thread-exit.c
add some helpers in heplers.c:
- io_uring_calloc()
- io_uring_posix_memalign()
- io_uring_create_file()
- io_uring_create_buffers()
and then we replace corresponding functions with helpers in tests.
Signed-off-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>
> helpers: add some helpers for tests

- examples/link-cp.c
Signed-off-by: David Disseldorp <ddiss@suse.de>
> examples/link-cp: fix a couple of strerror negations

- test/connect.c
> Fix test_connect_timeout

- test/io_uring_enter.c
`to_submit` argument probably should be 0
Signed-off-by: 신승훈 <seunghunee@gmail.com>
> test/io_uring_enter.c: set to_submit to 0

- test/Makefile
- test/sqpoll-cancel-hang.c
Added test and updated Makefile to include the test
Lore link on discussion : https://lore.kernel.org/io-uring/CAGyP=7cr1S462e+ZNQY_s3ygmHbYpRo6OLrx7RCLKX8h6F=OnQ@mail.gmail.com/
Signed-off-by: Palash Oswal <oswalpalash@gmail.com>
> add test for sqpoll cancel hang

- test/empty-eownerdead.c
- test/io_uring_register.c
- test/multicqes_drain.c
- test/runtests.sh
- test/timeout-new.c
This PR fixes a few test cases that were failing. And improves the runner to make it easier to track down these kinds of problems.
> Test suite fixes

- test/double-poll-crash.c
- test/fc2a85cb02ef-test.c
- test/sqpoll-cancel-hang.c
These will cause build failures on some systems.
> Syscall fixes

- .github/workflows/build.yml
- examples/io_uring-cp.c
- examples/link-cp.c
As these flags are marked as optional now they get reset when we pass
explicit flags.
Cc: @ammarfaizi2
> .github/workflows/build.yml: Pass -g -O2 -Wall -Wextra explicitly

- test/nop-all-sizes.c
- test/probe.c
Hello, thanks for liburing! I made little imrpovements for a couple of tests
> Minor improvements to some unit tests

- src/include/liburing.h
Signed-off-by: 李通洲 <carter.li@eoitek.com>
> liburing.h: add io_uring_prep_close_direct

- src/setup.c
I think such change makes it more clear
> setup.c: handmade fls -> __builtin_clz

- .github/pull_request_template.md
Hi Jens,
This pull request is a follow up for:
https://github.com/axboe/liburing/pull/464#issuecomment-950950688
I wrote a pull request template for liburing GitHub repo. The template
contains a basic pull request guidelines, such as commit message
format rules and the Linux kernel coding style.
If you think it looks good, please pull. Otherwise, tell me what to
fix.
When I wrote this pull request, I also use the template, so the result
of the template I wrote will look like this PR.
Cc: @isilence
-- 
Ammar Faizi
----
```
The following changes since commit 797a70034f2f163edbfcda229bf5a314572a6ea7:
Merge branch 'fix463' of https://github.com/tchaloupka/liburing (2021-10-25 07:51:44 -0600)
https://github.com/ammarfaizi2/liburing pr-template
for you to …
```
> [GIT PULL] .github: Create pull_request_template.md

- man/io_uring.7
> Remove unused variable in man page example

- examples/io_uring-cp.c
Add io_uring_submit after queue_prepped while re-queuing sqe.
Fixes: https://github.com/axboe/liburing/issues/503
Signed-off-by: monte <wm.april@gmail.com>
> [GIT PULL] examples/io_uring_cp: fix bug while re-queuing

- man/io_uring_prep_read.3
- man/io_uring_prep_readv.3
- man/io_uring_prep_readv2.3
- man/io_uring_prep_write.3
- man/io_uring_prep_writev.3
- man/io_uring_prep_writev2.3
----
```
The following changes since commit 7233a8753cb7a4a137cdc5e534bb31fb2a0d53fd:
test/getdents: ignore run if argument specified (2021-12-22 19:54:45 -0700)
git@github.com:ioquatix/liburing.git man-page-offset-clarification
for you to fetch changes up to 9ec56b9fb31d9f77fc23113ceda27d7b4cbad19e:
Clarify behaviour of offset in `prep_read`/`prep_write`. (2021-12-23 17:29:24 +1300)
Samuel Williams (1):
Clarify behaviour of offset in `prep_read`/`prep_write`.
man/io_uring_prep_read.3    | 17 +++++++++++++++--
man/io_uring_prep_readv.3   | 16 +++++++++++++++-
man/io_uring_prep_readv2.3  | 19 +++++++++++++++++--
man/io_uring_prep_write.3   | 17 +++++++++++++++-- …
```
> [GIT PULL] Clarify behaviour of offset in `prep_read`/`prep_write`.

- examples/ucontext-cp.c
- src/include/liburing.h
- test/eventfd-disable.c
- test/eventfd-reg.c
- test/eventfd-ring.c
- test/eventfd.c
- test/io-cancel.c
- test/io_uring_register.c
- test/iopoll.c
- test/link-timeout.c
- test/multicqes_drain.c
- test/poll-cancel-ton.c
- test/poll-cancel.c
- test/poll-many.c
- test/poll-mshot-update.c
- test/poll-ring.c
- test/poll-v-poll.c
- test/poll.c
- test/read-write.c
- test/register-restrictions.c
- test/ring-leak2.c
- test/sendmsg_fs_cve.c
- test/short-read.c
- test/shutdown.c
- test/sigfd-deadlock.c
- test/sq-poll-dup.c
- test/sq-poll-kthread.c
- test/sq-poll-share.c
- test/sqpoll-exit-hang.c
- test/thread-exit.c
Some simple changes to fix warnings/errors when compiling on Alpine Linux. To reproduce the issue:
```bash
docker run --rm -it alpine
apk add git g++ make linux-headers
git clone https://github.com/axboe/liburing
cd liburing && make
```
> Alpine linux compile fix

- SECURITY.md
Define an initial security policy in the file SECURITY.md.
The content of the file will become the content of the
page https://github.com/axboe/liburing/security/policy.
Fixes: https://github.com/axboe/liburing/issues/534
Signed-off-by: Dmitry Rozhkov <dmitry.rozhkov@intel.com>
----
```
The following changes since commit a339505f1dd3ea0d2626abdcfd44d6ddd56b41e3:
man/io_uring_prep_cancel.3: add io_uring_prep_poll_remove(3) to see also (2022-03-29 06:37:04 -0600)
git@github.com:rojkov/liburing.git master
for you to fetch changes up to 499b55f07f84a1e4282676a9cbf6f12dd4ce4b51:
Add SECURITY.md (2022-03-29 16:42:12 +0300)
Dmitry Rozhkov (1):
Add SECURITY.md
SECURITY.md | 6 ++++++
1 file …
```
> [GIT PULL] Add SECURITY.md

- man/io_uring_prep_linkat.3
- man/io_uring_prep_mkdirat.3
- man/io_uring_prep_renameat.3
- man/io_uring_prep_symlinkat.3
- man/io_uring_prep_unlinkat.3
- src/include/liburing.h
- test/rename.c
- test/unlink.c
This is done for unlink, rename, mkdir, symlink and link.
Signed-off-by: Usama Arif <usama.arif@bytedance.com>
> io_uring: add prep functions for current working directory

- man/io_uring_prep_madvise.3
The man page for `io_uring_prep_madvise` contains wrong function
signature and description. This commit fixes is by removing
the unused parameter.
Signed-off-by: Seiichi Uchida <topecongiro@fastmail.com>
----
```
The following changes since commit a7a51f3b36ea7f83f3d4efd922e86417546590f2:
Merge branch 'fix/man-accept' of https://github.com/topecongiro/liburing (2022-06-05 21:20:28 -0600)
https://github.com/topecongiro/liburing fix/man-madvise
for you to fetch changes up to b2399269447cef7e27362fcf2055486b0dd7410e:
man/io_uring_prep_madvise.3: remove fd (2022-06-06 17:23:25 +0900)
Seiichi Uchida (1):
man/io_uring_prep_madvise.3: remove fd
man/io_uring_prep_madvise.3 | 5 +----
1 file …
```
> [GIT PULL] man/io_uring_prep_madvise.3: remove fd

- src/queue.c
`io_uring_submit()` makes an `io_uring_enter()` syscall even if no SQEs are
ready to submit. Move the empty SQ check from `_io_uring_get_cqe()` to
`sq_ring_needs_enter()` so `io_uring_submit()` can skip the syscall too.
----
```
The following changes since commit b1486931117f643b0ad6612beb3f9563b508126c:
Merge branch 'refactor/cache-ring-size' of https://github.com/calebsander/liburing (2022-08-28 14:06:55 -0600)
git@github.com:calebsander/liburing.git feature/no-empty-submit
for you to fetch changes up to 504efe18c213dd753fe6c69afbfff6cfd50ba4cc:
queue: avoid io_uring_enter() with no SQEs (2022-08-28 19:04:53 -0600)
Caleb Sander (1):
queue: avoid io_uring_enter() with no SQEs …
```
> [GIT PULL] queue: avoid io_uring_enter() with no SQEs

- test/runtests.sh
Retain FAILED, SKIPPED and TIMED_OUT lists in Bash arrays so that the counts can be dumped alongside test names. Remove RET, which can be derived from non-zero FAILED length.
Signed-off-by: David Disseldorp <ddiss@suse.de>
----
```
The following changes since commit c7bd745bf7973806d81b966f35a3af6217433851:
test/rsrc_tags: turn assert into actual error logging (2022-09-23 09:14:39 -0600)
https://github.com/ddiss/liburing test_print_counts
for you to fetch changes up to d9198011103b293c7a9d96035ed510a8afeeb9b1:
test/runtests.sh: print failure / time-out counts (2022-09-23 23:49:43 +0200)
David Disseldorp (1):
test/runtests.sh: print failure / time-out counts
test/runtests.sh | 31 …
```
> [GIT PULL] test/runtests.sh: print failure / time-out counts

- man/io_uring_setup.2
----
```
The following changes since commit 65791341a5d7e79aa601c96be9df0e7ed4603e05:
Merge branch 'test_print_counts' of https://github.com/ddiss/liburing (2022-09-23 18:58:59 -0600)
https://github.com/jrudolph/liburing fix-IORING_SETUP_CQE32-desc
for you to fetch changes up to 9d076397b962821de53b74112ac24ed0fb16f5af:
man: fix typo in IORING_SETUP_CQE32 description (2022-09-25 10:31:55 +0200)
Johannes Rudolph (1):
man: fix typo in IORING_SETUP_CQE32 description
man/io_uring_setup.2 | 2 +-
```
----
<details>
1. To make everyone easily filter pull request from the email …
> [GIT PULL] man: fix typo in IORING_SETUP_CQE32 description

- man/io_uring_enter.2
Document the IORING_OP_SOCKET opcode in io_uring_enter.2
----
```
The following changes since commit 1c469ee303d0f458a6b039c9483865b3af248400:
man/io_uring_prep_accept.3: add note on multishot and addr/addrlen (2022-10-06 15:32:19 -0600)
https://github.com/ilikdoge/liburing master
for you to fetch changes up to 09b542e6939b5fb112de9e0b696b024b464944c4:
man/io_uring_enter.2: Add IORING_OP_SOCKET to the list of opcodes (2022-10-15 22:48:59 -0700)
ilikdoge (1):
man/io_uring_enter.2: Add IORING_OP_SOCKET to the list of opcodes
man/io_uring_enter.2 | 34 ++++++++++++++++++++++++++++++++++
1 file changed, 34 insertions(+)
```
----
<details> …
> [GIT PULL] Add IORING_OP_SOCKET to man io_uring_enter

- man/io_uring_submit_and_wait_timeout.3
Fixes: https://github.com/axboe/liburing/issues/684
Signed-off-by: David Zeng <ilikdoge0@gmail.com>
----
```
The following changes since commit 6bce6110e3a0de3e37342e780cfbf62e291c5672:
man: fixup missing entry annotations (2022-10-17 12:50:47 -0700)
https://github.com/ilikdoge/liburing.git master
for you to fetch changes up to fccfc930d582796029f7e91b8ce744e2729a22c2:
man/io_uring_submit_and_wait_timeout.3: fix return value description (2022-10-17 15:30:41 -0700)
ilikdoge (1):
man/io_uring_submit_and_wait_timeout.3: fix return value description
man/io_uring_submit_and_wait_timeout.3 | 6 +++++-
1 file changed, 5 insertions(+), 1 deletion(-)
```
----
<details>
<summary>Click to …
> [GIT PULL] man/io_uring_submit_and_wait_timeout.3: fix return value description

- man/io_uring_get_sqe.3
- man/io_uring_prep_nop.3
Fixes <https://github.com/axboe/liburing/issues/690>.
> Suggested documentation improvements.

- man/io_uring_get_sqe.3
What do you think of being a little bit more explicit here?
> Clarify that user_data is neither set nor cleared

- man/io_uring_register_files_sparse.3
Signed-off-by: Frank Rehwinkel <frankrehwinkel@gmail.com>
----
```
The following changes since commit d8416f5732e03cfaf0d5bdfd2b64ccd8db9e83d4:
Merge branch 'submit-and-wait-ts' (2022-10-22 15:13:19 -0600)
git@github.com:frankreh/liburing.git frankreh/link_io_uring_register_files_sparse
for you to fetch changes up to 2de081cb23d1fd887c29ef6a9de3ff1049ae51e1:
symlink man/io_uring_register_files_sparse.3 (2022-10-24 08:51:46 -0400)
Frank Rehwinkel (1):
symlink man/io_uring_register_files_sparse.3
man/io_uring_register_files_sparse.3 | 1 +
1 file changed, 1 insertion(+)
create mode 120000 man/io_uring_register_files_sparse.3
```
----
<details> …
> [GIT PULL] symlink man/io_uring_register_files_sparse.3

- test/send_recv.c
Small fix for leaked ring within send_recv.c test.
Added a call for io_uring_queue_exit() in the cleanup. 
----
```
The following changes since commit 9961f57f1fe58a343b8050fa504a0dd1d4fd6425:
liburing.spec: bump version to 2.4 (2022-11-01 19:52:25 -0600)
https://github.com/itaysnir/liburing master
for you to fetch changes up to fa366315ab499c05e6cc5f082b591a23098d721f:
yet another indentation (2022-11-04 04:59:19 -0400)
itaysnir (4):
fixed ring leak for do_send
changed indentation
added space
yet another indentation
test/send_recv.c | 14 ++++++++------
1 file changed, 8 insertions(+), 6 deletions(-)
```
----
<details>
1. To …
> [GIT PULL] Fixed leaked ring for send_recv test

- man/io_uring_wait_cqe_timeout.3
Signed-off-by: Dmitry Antipov <dantipov@cloudlinux.com>
> man: fix io_uring_wait_cqe_timeout() typo

- man/io_uring_prep_poll_add.3
Signed-off-by: Dmitry Antipov <dantipov@cloudlinux.com>
> man: fix io_uring_prep_poll_add() typo

- man/io_uring_prep_readv.3
- man/io_uring_prep_readv2.3
- man/io_uring_prep_writev.3
- man/io_uring_prep_writev2.3
Signed-off-by: Dmitry Antipov <dantipov@cloudlinux.com>
> man: fix io_uring_prep_{readv,writev}{2} typo

- man/io_uring_register.2
- man/io_uring_register_buf_ring.3
- removed a reference to a non-existent flags argument
- fixed macro case so that nr_args gets rendered
- improved grammar
----
```
The following changes since commit 5f0cf68fc2cd28617a86976fc906447f737086d5:
man/io_uring_setup.2: fix references to library/system calls (2022-12-08 16:24:12 -0700)
https://github.com/wlukowicz/liburing.git man-fixes
for you to fetch changes up to ec8cd0d0c46d6b2a1f17a2f5f4ad7b7d273db7e8:
man: fixed IORING_REGISTER_PBUF_RING description (2022-12-11 16:51:46 +0000)
Wojciech Lukowicz (1):
man: fixed IORING_REGISTER_PBUF_RING description
man/io_uring_register.2          | 10 +++-------
man/io_uring_register_buf_ring.3 |  4 ++--
2 files changed, 5 …
```
> [GIT PULL] man: fixed IORING_REGISTER_PBUF_RING description

- man/io_uring_buf_ring_add.3
- man/io_uring_prep_recv.3
- man/io_uring_prep_recvmsg.3
- man/io_uring_register_buf_ring.3
Several small man fixes:
- fix grammar in io_uring_prep_recv.3 and io_uring_prep_recvmsg.3
- fix function signature in io_uring_buf_ring_add.3
- fix references in io_uring_register_buf_ring.3
----
```
The following changes since commit e5bb0e647ae8e51e6da7d1673420c2faf822c932:
man/io_uring_setup.2: add not on SQPOLL and privileges (2022-12-24 07:38:17 -0700)
https://github.com/wlukowicz/liburing man-fixes
for you to fetch changes up to 071793cd1f837daced99227362488524f6a04e16:
man/io_uring_register_buf_ring.3: fix references (2022-12-26 17:06:50 +0000)
Wojciech Lukowicz (3):
man: fix grammar
man/io_uring_buf_ring_add.3: fix function signature
man/io_uring_register_buf_ring.3: fix …
```
> [GIT PULL] Several small man fixes

- man/io_uring_prep_recv.3
- man/io_uring_prep_recvmsg.3
- man/io_uring_recvmsg_out.3
**man/io_uring_recvmsg_out.3:**
- changed io_uring_prep_recv_multishot references to io_uring_prep_recvmsg_multishot, because only the latter uses such result layout
- added a paragraph explaining what msgh should be
- improved formatting
- fixed a typo
**man/io_uring_prep_recvmsg.3:**
- improved formatting
**man/io_uring_prep_recv.3:**
- fixed argument name
- improved grammar and formatting
----
```
The following changes since commit bfb432f4cce52cb3e3bd9c1823e94ff29bd4fb80:
configure: Always enable `CONFIG_NOLIBC` if the arch is supported (2023-01-06 15:39:04 -0700)
https://github.com/wlukowicz/liburing man-fixes
for you to fetch changes up to b82c5b77cd34edbfdb526b83ac1bad1935647299:
man/io_uring_prep_recv.3: fixes and improvements (2023-01-08 …
```
> [GIT PULL] Manual fixes and improvements

- .gitignore
- Makefile
- liburing-ffi.pc.in
- liburing.pc.in
- make-debs.sh
- test/sendmsg_fs_cve.c
Add a liburing-ffi.pc file to match the existing liburing.pc file. Fix the URLs (in particular the one in the liburing.pc) to use https:// instead of http://, to match the newly introduced liburing-ffi.pc file.
----
```
The following changes since commit 849f5ba89b0d1ccf9d825160bf8560ad9901c48b:
tests: lazy pollwq activation for disabled rings (2023-01-16 10:48:45 -0700)
https://github.com/guillemj/liburing pu/liburing-ffi.pc
for you to fetch changes up to e5bf65f5fad70d2d5734d1278c2d85fda2455cd6:
pkgconfig: Add a liburing-ffi.pc file (2023-01-18 02:58:52 +0100)
Guillem Jover (2):
Switch URLs from http to https
pkgconfig: Add a liburing-ffi.pc file
.gitignore            |  1 +
Makefile …
```
> [GIT PULL] Add liburing-ffi.pc file

- examples/send-zerocopy.c
- test/send-zerocopy.c
This header is not needed therefore remove it, this cleanup also helps compiling on musl/clang
/usr/include/linux/errqueue.h:57:20: error: array has incomplete element typ e 'struct timespec'
struct timespec ts[3];
^
----
```
The following changes since commit f5cac78e621ab452d3035902085f66d2bf73243b:
test/file-verify: remove duplicate include file (2023-02-16 19:45:20 -0700)
https://github.com/kraj/liburing master
for you to fetch changes up to 0fbcc44fe1fb2dc6807660b2cff1c2995add095b:
examples,test: Remove unused linux/errqueue.h (2023-02-18 18:02:25 -0800)
Khem Raj (1):
examples,test: Remove unused linux/errqueue.h
examples/send-zerocopy.c | 1 -
test/send-zerocopy.c     | 1 -
2 …
```
> [GIT PULL] examples,test: Remove unused linux/errqueue.h

- configure
- src/Makefile
- src/arch/riscv64/lib.h
- src/arch/riscv64/syscall.h
- src/lib.h
- src/syscall.h
- test/nolibc.c
----
```
The following changes since commit 660cefae669c985aeaeaf50e45b635777ac40edc:
test/wq-aff: add test case for SQPOLL io-wq affinity (2023-08-14 08:21:02 -0600)
https://github.com/michalbiesek/liburing.git feat-riscv64-nolibc
for you to fetch changes up to d305ed56ae6008be975e029740f8338f8f66587a:
Add nolibc riscv64 support (2023-08-23 13:00:25 +0200)
Michal Biesek (1):
Add nolibc riscv64 support
configure                  |   4 +--
src/Makefile               |   2 +-
src/arch/riscv64/lib.h     |  48 ++++++++++++++++++++++++++++++
src/arch/riscv64/syscall.h | 100 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
src/lib.h                  |   2 ++
src/syscall.h …
```
> Add nolibc riscv64 support

- .github/workflows/build.yml
- .github/workflows/shellcheck.yml
address the following warning:
"The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2."
----
```
The following changes since commit 921c430b0f4ad29c62af65b428a89ecb7dfbfe65:
Merge branch 'feat-riscv64-nolibc' of https://github.com/michalbiesek/liburing (2023-08-23 09:27:10 -0600)
https://github.com/michalbiesek/liburing.git feat-ci-node-fix
for you to fetch changes up to 0a752011511ec146664bf112501ca2ace3650e69:
github: update `actions/checkout` version v2 -> v3 (2023-08-23 17:33:50 +0200)
Michal Biesek (1):
github: update `actions/checkout` version v2 -> v3
.github/workflows/build.yml      | 2 +-
.github/workflows/shellcheck.yml …
```
> github: update `actions/checkout` version v2 -> v3

- liburing.spec
%{_libdir} is always an absolute path, so there is no need to prefix it with "/". in general, it does not hurt. but this extra slash would be written into .pc file, so the generated .pc file would look like:
```
libdir=//usr/lib64
```
which is not quite perfect. so let's drop the heading "/".
----
```
The following changes since commit b58921e0b0ae84b6f1cd22b87c66a6e91a540ec8:
Merge branch 'uring_sysctl' of https://github.com/matrizzo/liburing (2023-09-13 08:11:53 -0600)
git@github.com:tchaikov/liburing.git remove-dup-slash
for you to fetch changes up to be96a8fcba45ea6d8d23239d7cb9e2a62651c354:
spec: do not add "/" before %{_libdir} (2023-09-28 12:57:58 +0800)
Kefu Chai (1):
spec: do …
```
> spec: do not add "/" before %{_libdir}

- test/hardlink.c
This is a test for https://github.com/axboe/liburing/issues/955. On kernels without the fix, the test is skipped.
It tests `AT_SYMLINK_FOLLOW` only, as `AT_EMPTY_PATH` requires `CAP_DAC_READ_SEARCH`.
Signed-off-by: Thomas Leonard <talex5@gmail.com>
----
```
The following changes since commit b3ee3e764593ea85ba88f00b77bab2d58fbca530:
Merge branch 'remove-dup-slash' of https://github.com/tchaikov/liburing (2023-09-28 02:47:20 -0600)
https://github.com/talex5/liburing.git hardlink-flags
for you to fetch changes up to 5228f7a3025fca90d45d109912ba7a9711fe5407:
Add test for passing flags to linkat (2023-09-29 10:48:24 +0100)
Thomas Leonard (1):
Add test for passing flags to linkat …
```
> [GIT PULL] Add test for passing flags to linkat

- README
- make-debs.sh
- man/io_uring_queue_init.3
- man/io_uring_register.2
- src/setup.c
- test/eventfd-reg.c
- test/file-verify.c
- test/multicqes_drain.c
- test/socket-getsetsock-cmd.c
----
```
The following changes since commit 9dc95a03e4a764e42b9e62990bb00feb9307ba63:
test/no-mmap-inval: 0 return is fine too (2023-11-07 08:05:52 -0700)
https://github.com/guillemj/liburing pu/typos
for you to fetch changes up to 2c89b57f3d55b2e3098a629e8aabe659fd5ec138:
Fix typos (2023-11-10 01:49:41 +0100)
Guillem Jover (2):
man/io_uring_queue_init.3: Fix typo
Fix typos
README                       | 2 +-
make-debs.sh                 | 2 +-
man/io_uring_queue_init.3    | 2 +-
man/io_uring_register.2      | 2 +-
src/setup.c                  | 2 +-
test/eventfd-reg.c           | 2 +-
test/file-verify.c           | 2 +-
test/multicqes_drain.c       | 2 +-
test/socket-getsetsock-cmd.c …
```
> [GIT PULL] Typo fixes

- test/openat2.c
`test/openat2.c` tests `openat2(2)`. But, before this fix, the description said "run various openat(2) tests" (i.e. there was a "2" missing immediately after "openat"!)
This PR changes the file's description to: "run various openat2(2) tests".
----
```
The following changes since commit 53141161ad930b25f6e5f8f7111c392ac163bf71:
Merge branch 'napi' (2024-02-09 11:55:51 -0700)
https://github.com/JackKelly/liburing fix_typo_in_description
for you to fetch changes up to e0cd9a5164e98e514bd443f4d177a83c1008a818:
test/openat2.c: fix tiny typo in description. (2024-02-12 19:27:28 +0000)
Jack Kelly (1):
test/openat2.c: fix tiny typo in description.
test/openat2.c | 2 +-
1 file changed, 1 …
```
> [GIT PULL] test/openat2.c: fix tiny typo in description.

- examples/proxy.c
- **examples/proxy: use -H instead of -h for remote host**
It seems there was an innocent typo `-h` instead of `-H`.
----
```
The following changes since commit 4ef5e451e4bd21c5f5325c9a625fdc1754c0c76c:
examples/proxy: fix silly error in grabbing an SQE twice (2024-02-17 18:59:28 -0700)
https://github.com/mfrw/liburing mfrw/fix-typo-in-usage
for you to fetch changes up to 0193feb0ffd0fcf93f0347869bbd3615c7274a9c:
examples/proxy: use -H instead of -h for remote host (2024-02-18 09:41:23 +0530)
Muhammad Falak R Wani (1):
examples/proxy: use -H instead of -h for remote host
examples/proxy.c | 2 +-
```
----
<details>
<summary>Click to show/hide …
> [GIT PULL] examples/proxy: use -H instead of -h for remote host

- .github/workflows/build.yml
- .github/workflows/codespell.yml
- .github/workflows/shellcheck.yml
The version 3 action was generating deprecation warnings about Node.js.
----
```
The following changes since commit b08194d7e4cdfe1717af90ab067a4d62945d5180:
test/fdinfo: add fdinfo reading test case (2024-08-27 12:13:54 -0600)
https://github.com/guillemj/liburing.git pu/ci-update
for you to fetch changes up to 96cbb396b6bac6122fa7d813ef3e96cc19be7456:
.github: Bump actions/checkout to version 4 (2024-08-27 21:08:31 +0200)
Guillem Jover (1):
.github: Bump actions/checkout to version 4
.github/workflows/build.yml      | 2 +-
.github/workflows/codespell.yml  | 2 +-
.github/workflows/shellcheck.yml | 2 +-
3 files changed, 3 insertions(+), 3 deletions(-)
```
----
<details>
<summary>Click …
> [GIT PULL] .github: Bump actions/checkout to version 4

- man/io_uring_register.2
This adds documentation for:
1. IORING_REGISTER_NAPI
2. IORING_UNREGISTER_NAPI
3. IORING_REGISTER_PBUF_STATUS
4. Some related errors
Also fixes various fmting errors/inconsistencies.
----
```
The following changes since commit de5bf97204646ed7b35da2968ce12b5923155af8:
test/wq-aff: test for SQPOLL affinity with deliberately large CPU (2024-09-16 02:53:34 -0600)
https://github.com/CPestka/liburing io_uring_register_man
for you to fetch changes up to d47905331ca1f1183f94f5f800b7ee48f2fd53cf:
man/io_uring_register: Various formatting fixes (2024-09-16 17:33:29 +0200)
CPestka (4):
man/io_uring_register: Add docs for IORING_REGISTER_PBUF_STATUS
man/io_uring_register: Add doc for registering …
```
> [GIT PULL] man/io_uring_register: Add docs for pbuf status and napi (un)register

- test/init-mem.c
- test/ooo-file-unreg.c
trivial fixes that gets going on musl systems.
> Musl fixes in tests

- man/io_uring_setup.2
This adds:
1. Docs for IORING_FEAT_RECVSEND_BUNDLE
2. A missing error code
3. A remark for attach wq that the sq poll thread is also shared
4. fmt fixes
to the man page of io_uring_setup.
----
```
The following changes since commit 66e7618a900b172f464cde132548fecbfc09f8cd:
test/linked-defer-close: ignore argument passed in (2024-09-20 02:47:51 -0600)
https://github.com/CPestka/liburing io_uring_setup_man
for you to fetch changes up to 571ad06dc8e931747c8d65326212e3ae1d3ffb6f:
man/io_uring_setup: Add doc for IORING_FEAT_RECVSEND_BUNDLE (2024-09-20 13:25:44 +0200)
CPestka (4):
man/io_uring_setup: Add remark about SQ poll thread with ATTACH_WQ
man/io_uring_setup: Fix formatting …
```
> [GIT PULL] man/io_uring_setup: Add missing feat, fmt etc.

- man/io_uring_enter.2
The man pages reference `unlinkat2`, `mkdirat2`, `symlinkat2`, and `linkat2` which I think are typos. This fixes them by removing the `2`.
Related to https://github.com/tokio-rs/io-uring/pull/304
There are also a few references to `futex2(2)` which I now understand (I think) refers to the group `futex_{wait,waitv,wake}`, but unfortunately none of those have man pages. Is there a place that documents those that the `futex2(2)` link could reference instead?
----
```
The following changes since commit 0c8975ad7c95de0f81a9dc869b55e77131159040:
man/io_uring_register_ring_fd: add note about kernel availability (2024-09-22 00:47:34 -0600)
https://github.com/aconz2/liburing fix-man-pages2
for you to fetch changes up to …
```
> [GIT PULL] Fix some syscall name typos in man pages

- man/io_uring_prep_open.3
- man/io_uring_prep_open_direct.3
- man/io_uring_prep_openat.3
- src/include/liburing.h
- src/liburing-ffi.map
Adds the direct and regular open prep helper as two small wrapper functions around the openat prep helper.
Also adds the links for them in the man pages.
Would close #1100 
----
```
The following changes since commit 206650ff72b6ea4d76921f9c91ebfffd9902e6a0:
test/fixed-hugepage: skip test on -ENOMEM (2024-09-27 10:27:10 -0600)
https://github.com/CPestka/liburing open_helper
for you to fetch changes up to 48ca808a97556e1d1e25d6b5f924c7881ca1f367:
man/prep_open: Add man entry for io_uring_prep_open(_direct) (2024-09-29 13:27:55 +0200)
CPestka (2):
liburing/sqe_helper: Add helper to prep sqe for an open
man/prep_open: Add man entry for io_uring_prep_open(_direct)
man/io_uring_prep_open.3 …
```
> [GIT PULL] Liburing/prep_helpers: Add Open helpers

- examples/send-zerocopy.c
`-s` arg was already described in previous line.
----
```
The following changes since commit a27cad82c6c1ffb4a387967ff4b088509e10303f:
.gitignore: Add compilation database file and directory (2024-11-06 07:52:40 -0700)
https://github.com/gmelikov/liburing.git typo
for you to fetch changes up to 978db5fc716d5812f1171265f6db937e75223f0a:
examples/send-zerocopy.c: remove duplicate line in usage (2024-11-15 01:00:36 +0300)
George Melikov (1):
examples/send-zerocopy.c: remove duplicate line in usage
examples/send-zerocopy.c | 1 -
1 file changed, 1 deletion(-)
```
----
<details>
1. To make everyone easily filter pull request from …
> [GIT PULL] examples/send-zerocopy.c: remove duplicate line in usage

- test/sendmsg_iov_clean.c
Builds with address sanitizer seem to flag this test, noting an access to the msghdr struct used in queue_sends(). This is because the address of the stack-local is written to the SQE and placed in the SQ. Because submission is not done in this stack frame, we wind up submitting SQEs with addresses to long-dead stack-locals.
This commit relocates the msghdr struct along with the backing I/O vectors to the same frame that does submission and asan becomes happy with the test.
The output of asan that I see with gcc-13 through gcc-15 is:
```
exbigboss@pleiades ~/c/liburing (master)> ./test/sendmsg_iov_clean.t
Address 0x78d103d00070 is located in stack of thread T0 at offset 112 in frame
#0 0x604fd184ae1f in main /home/exbigboss/cpp/liburing/test/sendmsg_iov_clean.c:117
This frame has 9 …
```
> [GIT PULL] test/sendmsg_iov_clean: fix stack use-after-free
