examples/Makefile
examples/ucontext-cp.c

Coroutines are often used to simplify async programming,
and they work great with liburing.
`ucontext` doesn't perform very good, but it's enough for an example.

examples/ucontext-cp: use ucontext with liburing

---

src/queue.c

Always initialize `flags`
Signed-off-by: 李通洲 <carter.li@eoitek.com>

queue.c: Silence compiler warnings

---

test/statx.c

statx_timestamp is defined in both linux/stat.h and sys/stat.h,
causing a build failure on some systems

Fix redefinition of statx_timestamp

---

test/open-close.c

flags for read only should be placed in fourth position instead of fifth
one, which is for `mode`.

test: fix openat flags

---

man/io_uring_enter.2

The document for `IORING_OP_CONNECT` seems incorrect, addrlen should be stored in `off` instead of `len`.
I noticed that kernel [actually read `addr2`](https://github.com/torvalds/linux/blob/5cf9ad0e6b164a90581a59609dbf5bda3f5a089c/fs/io_uring.c#L2439), and I'm not sure which is better.

Fix IORING_OP_CONNECT document

---

.gitignore
test/Makefile
test/send_recv.c

Also ensure that `test/send_recvmsg.c` the recv thread finishs
before the process exits
Fixes https://github.com/axboe/liburing/issues/63

test: add test for send_recv

---

src/liburing.map

This version node is disconnected from LIBURING_0.2, and contains a
merged duplication of the LIBURING_0.1 and LIBURING_0.2 version nodes,
plus few local entries.
Remove its contents and link it to the LIBURING_0.2, as it will inherit
everything there in addition to the catchall local in LIBURING_0.1.
This leaves an empty version node around, and while it is a bit of an
oddity and it might be somewhat safe to remove, it could still break
users. So we leave it behind as a representation of what went on in
that release.

liburing.map: Fix LIBURING_0.3 shared library version node

---

src/include/liburing/barrier.h

`io_uring_smp_store_release()` and `io_uring_smp_load_acquire()` currently issue full sequentially consistent memory barriers (as opposed to release and acquire barriers, respectively) on every architecture except x86(-64) and 64-bit ARM.
These macros can instead be implemented using [GCC's `__atomic` builtins](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html), which were [introduced in GCC 4.7](https://gcc.gnu.org/gcc-4.7/changes.html). This ensures that the proper, most optimal instructions are used for every architecture that GCC supports.
Given that io_uring first appeared in Linux 5.1, it seems very unlikely that anyone will need to compile liburing with any version of GCC prior to 4.7, which was released in 2012.
I haven't observed any regressions on my machine, …

Use __atomic builtins in barrier.h for better architecture support

---

test/Makefile

On certain architectures, like ppc64, `__u64` is a typedef of `unsigned long` rather than `unsigned long long`, which causes warnings when compiling tests that use the `%llu` printf specifier:
```
link-timeout.c:594:29: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘__u64’ {aka ‘long unsigned int’} [-Wformat=]
594 |     fprintf(stderr, "Req %llu got %d\n", cqe->user_data,
|                          ~~~^            ~~~~~~~~~~~~~~
|                             |               |
|                             |               __u64 {aka long unsigned int}
|                             long long unsigned int
|                          %lu
```
If `__SANE_USERSPACE_TYPES__` is defined before including \<linux/types.h\>, `__u64` will instead be a …

Fix warnings when compiling tests on certain architectures

---

COPYING.GPL
liburing.spec
man/io_uring_enter.2
man/io_uring_register.2
man/io_uring_setup.2

This series try to clarify the current licensing situation, with the objective of then being able to upload this to Debian. I've tried to infer the correct licenses from the stuff in the repo as a starting point, but probably my guesses are wrong, I'm happy to amend any of them.
I think the spec file syntax is correct, but I've not run rpmlint.
I've also left the debian directory alone for now which contains incorrect licensing data, with invalid syntax, as packaged this project from scratch anyway, and I'm not sure whether there's value in shipping the packaging upstream? So perhaps a better option is to remove it? But if you want to preserve it, I could prepare a targeted fix for just the copyright file though.

Clarify licensing

---

test/lfs-openat.c

This triggers a bug present until at least Linux 5.6.11, causing
EBADF, see https://lkml.org/lkml/2020/5/7/1287
Signed-off-by: Max Kellermann <mk@cm4all.com>

test/lfs-openat: open dfd with O_PATH

---

man/io_uring_enter.2

The interface to splice(2) in io_uring differs in that it doesn't accept a
pointer for the offset values, but instead a literal loff_t. It then uses a
sentinel value of -1 to pass the equivalent of a NULL. This fixes
io_uring_enter.2 to clarify this.

man: fix description of splice offsets

---

examples/ucontext-cp.c
man/io_uring_enter.2

examples/ucontext-cp.c: use IORING_OP_TIMEOUT

man/io_uring_enter: correct the description of IORING_OP_TIMEOUT with off == 0

---

src/include/liburing.h

This is the same as the underlying `connect` system call and fixes #151

Take `sockaddr` immutably in io_uring_prep_connect

---

README

liburing library seems redundant, this pull makes it more readable.
Signed-off-by: James Dominic P. Guana <guana.histark@gmail.com>

Make readme sensible

---

Makefile.quiet
test/Makefile
test/runtests.sh

Some fixes and improvements to the test suite build system.
In particular the patch about splitting each entry into its own line, will probably be useful to temporarily disable or conditionalize tests that are for now expected to fail in some conditions, such as VMs or other virtualization.

Test suite build improvements and fixes

---

src/include/liburing.h
src/liburing.map
src/setup.c

liburing has a convenience function to get a io_uring_probe that can
be used to test for valid features. The function returns a probe that
the caller has to then deallocate.
That's not a problem if we are dealing with languanges like C and C++
but when trying to uring liburing bindings in languages with a more
well defined barrier into the C interface, calling free() can be at
best cumbersome and at worst just wrong as the language may be using
a different allocator under the hood.
Since we provide an allocated version of probe, provide users with
a way to deallocate it.

probes: provide our own free function

---

Makefile
debian/liburing-dev.manpages
liburing.spec
man/io_uring_queue_exit.3
man/io_uring_queue_init.3

This PR is to add the first two API reference man pages as requested in
https://github.com/axboe/liburing/issues/190
It may take a while to get through all of these so I think it makes more sense
to add them piecemeal.
Note the `TODO` comments. I looked at how another library (libcurl) formats its
title section and they put the release version and release date; however, that
would be a pain to keep updated without proper tooling. Let me know how you
would prefer that to be formatted for liburing.
Also, I'm not familiar with Debian packaging but did my best to update that as
well; it's currently untested as I'll need to figure out how to do that.

Add section 3 man pages for init and exit

---

.gitignore
examples/Makefile
src/Makefile
test/Makefile

Fixes build flags settings, by honoring CPPFLAGS, and matches the CXXFLAGS handling with the other flags. In addition adds a missing ignore into .gitignore.

Build system fixes

---

configure

The RANDOM variable is a bashism, but we are using a /bin/sh as a
shebang, which means the temporary files created when /bin/sh is not
bash will be using unsafe and predictable names.
Switch to use mktemp(1) and its built-in temporary directory handling
instead of open-coding it.

configure: Fix unsafe temporary file creation

---

test/232c93d07b74-test.c
test/accept-link.c
test/accept-reuse.c
test/accept-test.c
test/accept.c
test/fixed-link.c
test/poll-link.c
test/shutdown.c
test/socket-rw-eagain.c
test/socket-rw.c

assert() is redefined as check() in liburing.h to ensure that it
will run if NDEBUG is defined. Without this, certain tests will
fail due to functions being called within an assert(), which are
skipped if NDEBUG is defined.
check() is a macro that will use assert() if NDEBUG is not defined.
Otherwise, it uses its own implementation.

Moves function calls out of assert() to run tests outside debug mode.

---

test/35fa71a030ca-test.c

It uses SYS_futex, which it expects from system C library.
in glibc (/usr/include/bits/syscall.h defines it in terms of of NR_futex)
rv32 is using 64bit time_t from get go unlike other 32bit architectures
in glibc, therefore it wont have NR_futex defined but just NR_futex_time64
this aliases it to NR_futex so that SYS_futex is then defined for rv32
Signed-off-by: Khem Raj <raj.khem@gmail.com>

test: Fix build on 32bit architectures with 6bit time_t

---

test/accept-link.c
test/cq-peek-batch.c
test/fallocate.c
test/link-timeout.c
test/poll-link.c
test/register-restrictions.c

6 liburing tests failed to build on powerpc due to a 'long' versus
'long long' mismatch. Changing the identifer from %lld to %PRIu64
and casting the value to uint64_t fixes this.

Changes format string from %lld to %PRIu64 in several tests.

---

src/include/liburing.h
src/queue.c

If heavy IO load then kernel thread will only very rarely need to be woken up. Only case where this condition is common is if timeout expected between IO calls in which case should be using GETEVENTS.
Have seen this condition get optimized for (compiler puts it as the fall through case).
Possible worth considering wrapping some of the error checking with this?

Add __builtin_expect(cond, 0) to NEED_WAKEUP for SQPOLL.

---

man/io_uring_enter.2

`addr` must in fact contain the length.
`len` is used for the fallocate mode.
See: https://patchwork.kernel.org/project/linux-fsdevel/patch/20191213183632.19441-2-axboe@kernel.dk/
Signed-off-by: Joran Dirk Greef <joran@coil.com>

Fix IORING_OP_FALLOCATE args in io_uring_enter(2) man page

---

man/io_uring_register.2
test/file-register.c

This is to add testing / documentation for patch: ```0001-io_uring-Add-skip-option-for-__io_sqe_files_update.patch``` if it is applied.
Should not be accepted unless the patch is as well.

Adding support for skipping files in kernel patch. This will add tests / documentation for said patch.

---

src/include/liburing.h

`sigset_t` requires `_XOPEN_SOURCE` to be bigger or equal to `500`.
This will fix #287

Fix sigset_t not found in liburing.h

---

src/queue.c

since we don't use it internally
Signed-off-by: 李通洲 <carter.li@eoitek.com>

src/queue.c: don't test `LIBURING_UDATA_TIMEOUT` for the latest kernel

---

src/setup.c

In io_uring_get_probe_ring func, we will call malloc()
to alloc memory for probe. Considering malloc may return NULL,
we should check whether malloc() succ before using it.
Signed-off-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>

setup: check whether malloc succ before using it

---

test/Makefile
test/accept.c
test/cq-overflow.c
test/d4ae271dfaae-test.c
test/defer.c
test/eeed8b54e0df-test.c
test/fadvise.c
test/file-register.c
test/file-update.c
test/fixed-link.c
test/fsync.c
test/helpers.c
test/helpers.h
test/io-cancel.c
test/io_uring_enter.c
test/io_uring_register.c
test/iopoll.c
test/link_drain.c
test/madvise.c
test/open-close.c
test/openat2.c
test/read-write.c
test/short-read.c
test/sq-poll-dup.c
test/sq-poll-share.c
test/statx.c
test/submit-reuse.c
test/thread-exit.c

As axboe said, Right now a lot of basic stuff is duplicated,
and it makes the tests bigger than they should be.
Here, we try to add helpers.h which will contains various
utilities that tests could use, then that'd help make tests simpler.
In this patch, we just add one helper io_uring_malloc(), which
will call assert() if allocating memory fails.
We will add more helpers in subsequent patches
Signed-off-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>

tests: add helpers.h to harden the tests

---

test/across-fork.c

This case was recently broken in kernel commit 41be53e94fb0 and
repaired in 8e5c66c485a8. As it's trivial to test...
Signed-off-by: Andres Freund <andres@anarazel.de>

tests: add test for using ring after a forked child exits.

---

man/io_uring_queue_exit.3

Fixes #337, incorrect return result in the synopsis of man
io_uring_queue_exit, and misplaced quote.
Signed-off-by: Emmanuel Le Trong <emmanuel.le-trong@cnrs-orleans.fr>

man: Fix typo in man io_uring_queue_exit

---

debian/rules

Otherwise the link created by
ln -sf $(relativelibdir)$(libname) $(libdevdir)/liburing.so
during make install will be invalid.

debian/rules: add missing slash for relativelibdir

---

test/ring-leak2.c

Fix a bug due to the unreleased lock before the function returns by inserting unlock statement before breaking.
Signed-off-by: Anson Lo ycaibb@gmail.com

Fix a bug due to the unreleased lock before function returns

---

man/io_uring_enter.2

In the section describing the IORING_OP_ACCEPT flag.

Refer to the accept_flags in io_uring_enter manual

---

man/io_uring_enter.2

One could (and did) interpret that cqe->res mathes the return *value* of preadv2 and pwritev2.
Clarify that it matches the errno values used by these two.

Clarify information about error results

---

test/file-register.c

When `test_basic` is called with `fail == 1`, the allocated array for
it is just 10, but the close_files is always called with 100.
Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>

test/file-register: fix heap overflow read on test_basic

---

.gitignore
test/file-update.c
test/fsync.c
test/helpers.h

```
Hi Jens,
After running the tests, we have these untracked files that shouldn't be
commited:
test/multicqes_drain
test/poll-mshot-update
test/rsrc_tags
test/rw_merge_test
test/sqpoll-cancel-hang
test/testfile
Add them to .gitignore. The rest commits are trivial memory leak fixes
for test. I also add a new helper macro `ARRAY_SIZE`.
-------
The following changes since commit 0ea4ccd1c0e4bb05cb4471d64e55d2e7d4e8a24c:
src/queue: don't flush SQ ring for new wait interface (2021-08-08 21:44:48 -0600)
https://github.com/ammarfaizi2/liburing ammarfaizi2-liburing-dev
for you to fetch changes up to f0230dc3fcbd54d9a371553f84f97db8092556ce:
test/file-update: clean up t_malloc() before return (2021-08-09 18:51:41 +0700) …
```

Add untracked test files to .gitignore and trivial memory leak fixes

---

src/syscall.c

I want to use iouring in mips, find some problem include kernel and library. 
Signed-off-by: wangyangbo <wangyangbo@uniontech.com>

correct syscall NR in mips

---

configure

Elbrus 2000 (aka e2k) is a 64-bit little-endian architecture. For several reasons it use makecontext_e2k(ctx, ...) with different semantic instead of makecontext(ctx, ...).

examples: disable ucontext-cp for elbrus (e2k) architecture

---

man/io_uring.7
man/io_uring_enter.2
man/io_uring_register.2

Hi Jens,
Trivial man clean up from me before 2.1 release.
Please pull.
```
The following changes since commit bb75e12e9bb628b62c13149478035b37acd518b5:
man/io_uring_enter.2: add notes about direct open/accept (2021-08-31 15:22:39 -0600)
https://github.com/ammarfaizi2/liburing man-page-fixes
for you to fetch changes up to 4c5987928e8df326e682c85e7deff557c0d0eebd:
man: clean up spelling (2021-09-01 09:45:27 +0700)
Ammar Faizi (1):
man: clean up spelling
man/io_uring.7          | 4 ++--
man/io_uring_enter.2    | 4 ++--
man/io_uring_register.2 | 2 +-
3 files changed, 5 insertions(+), 5 deletions(-)
```

[GIT PULL] man: clean up spelling

---

examples/Makefile
src/Makefile
test/Makefile

Closes #422 
Needed for e.g. musl libc which only includes entities like `cpu_set_t` if this is defined.

build: add -D_GNU_SOURCE to all CPPFLAGS/CFLAGS.

---

test/runtests-loop.sh
test/runtests.sh

I noticed the "! -z" oddness, and after fixing it decided to have a go with shellcheck, which resulted in this patch series.
I'm also thinking this would be nice to run as part of the repo's CI, which I notice is marked as failing, and I assume travis is not working either given their recent policy change. If you have no issue with this, I'd probably work tomorrow on switching these to use github actions?

Test suite shellcheck fixes

---

.github/workflows/build_with_clang.yml
.github/workflows/build_with_gcc.yml

Hi Jens,
Following up about the CI in https://github.com/axboe/liburing/pull/425#issuecomment-914540396
I wired up the GitHub Actions CI. This will build the lib and tests. But it doesn't perform the `make runtests` due to kernel limitation reason.
There are 2 builds:
1) Build with GCC.
2) Build with Clang.
Both uses `CFLAGS="-Werror" CPPFLAGS="-Werror" CXXFLAGS="-Werror"` to make sure the build is totally clean from warnings.
Extra note:
There was very specific warning from clang that caused the build fail. It is fixed in commit 008ccce8858aa620315aba71e6d2b332dff5a39c ("build_with_clang.yml: fix clang build error -Wunused-command-line-argument").
The CI runs well on my fork repo, you can take a look here:
Build with Clang: https://github.com/ammarfaizi2/liburing/runs/3573032633
Build …

[RFC][GIT PULL] Use GitHub Actions as CI (build only)

---

.github/workflows/build_with_clang.yml
.github/workflows/build_with_gcc.yml
configure
test/io_uring_register.c

Hi Jens,
Louvian reported that on some systems, glibc doesn't provide the wrapper
for `memfd_create(2)`. This pull request contains a fix for that and extra
small CI fix.
Compiler message:
```
io_uring_register.c: In function 'test_shmem':
io_uring_register.c:514:10: warning: implicit declaration of function 'memfd_create' [-Wimplicit-function-declaration]
memfd = memfd_create("uring-shmem-test", 0);
^
```
Please pull.
Cc: @louvian
```
The following changes since commit 6401b3149ff49458cf4fd330d74ff22abd90cb07:
Merge branch 'github-actions-ci' of https://github.com/ammarfaizi2/liburing (2021-09-10 21:25:21 -0600)
https://github.com/ammarfaizi2/liburing fix-test-shmem
for you to fetch …
```

[GIT PULL] Fix test shmem and extra small CI fix

---

.github/workflows/build.yml

Hi Jens,
Please pull 32-bit build for CI.
```
The following changes since commit d859ae0dd023dd37a12be30bfe0a7bca6dd4140a:
test/file-verify: add provide buffers support for main test too (2021-09-16 12:04:29 -0600)
https://github.com/ammarfaizi2/liburing ci-add-32-bit-build
for you to fetch changes up to dd5b44c509c9833da8bd283c3857b41bfe8bafe8:
.github/workflows/build.yml: add 32-bit build (2021-09-18 05:14:47 +0700)
Ammar Faizi (1):
.github/workflows/build.yml: add 32-bit build
.github/workflows/build.yml | 19 ++++++++++++++-----
1 file changed, 14 insertions(+), 5 deletions(-)
```

[GIT PULL] .github/workflows/build.yml: add 32-bit build

---

examples/ucontext-cp.c

glibc 2.34 has removed SIGSTKSZ therefore we replace it
Signed-off-by: Khem Raj <raj.khem@gmail.com>

examples/ucontext-cp.c: Do not use SIGSTKSZ

---

man/io_uring_setup.2

Add missing `wq_fd` field for `struct io_uring_params`.
Fixes: https://github.com/axboe/liburing/issues/473
Signed-off-by: Luchen Yang <ylc991@163.com>
----
```
The following changes since commit bceaacc35f9e75469f6179d63436d67dc5bd47d0:
test/Makefile: Refactor the Makefile (2021-10-31 16:30:00 -0600)
https://github.com/GalaxySnail/liburing pr1
for you to fetch changes up to b0f1f96823ae33648c267115989ea61f29d25e2c:
man/io_uring_setup.2: add missing `wq_fd` field (2021-11-05 23:30:39 +0800)
GalaxySnail (1):
man/io_uring_setup.2: add missing `wq_fd` field
man/io_uring_setup.2 | 3 ++-
1 file changed, 2 insertions(+), 1 deletion(-)
```
----
<details>
<summary>Click to show/hide pull …

man/io_uring_setup.2: add missing `wq_fd` field

---

configure
src/include/liburing.h
test/Makefile
test/file-verify.c
test/rename.c
test/unlink.c

fix build error related to statx when using glibc >= 2.28 
```
The following changes since commit a0039bd99910b3a9e28c8c70a52cadbd69e7c0f0:
Merge branch 'unused-var-man' of https://github.com/yinan1048576/liburing (2021-11-12 09:29:24 -0700)
origin/glibc-statx
for you to fetch changes up to 986ca17139c5dc1678256ae252d3c204881557bb:
fix 'make' when using glibc >= 2.28 (2021-11-12 17:28:32 +0000)
Bikal Lem (1):
fix 'make' when using glibc >= 2.28
configure              | 31 ++++++++++++++++++++++++++++++-
src/include/liburing.h |  1 -
test/Makefile          |  6 +++++-
3 files changed, 35 insertions(+), 3 deletions(-)
```

[GIT PULL] fix build error related to statx when using glibc >= 2.28 

---

test/runtests-loop.sh
test/runtests.sh

fixes `make runtests`.
```
The following changes since commit 28e631994a6770072b833e27ec0f2f75b29de305:
Merge branch 'glibc-statx' of https://github.com/bikallem/liburing (2021-11-12 11:26:54 -0700)
origin/fix-make-tests
for you to fetch changes up to 17c23393b6367e40c04299a9d67e4cab65273e66:
fix 'make runtests` (2021-11-12 18:37:12 +0000)
Bikal Lem (1):
fix 'make runtests`
test/runtests-loop.sh | 2 +-
test/runtests.sh      | 2 +-
2 files changed, 2 insertions(+), 2 deletions(-)
```

fix 'make runtests`

---

Makefile
Makefile.common
liburing.spec
src/Makefile

This PR ensures that we use VERSION variable consistently and correctly in Makefiles.
```
The following changes since commit b7159e46bc002c7a174e184d94cfa61552f92e69:
Merge branch 'fix-make-tests' of https://github.com/bikallem/liburing (2021-11-12 11:51:45 -0700)
origin/version
for you to fetch changes up to c0b43df28a982747e081343f23289357ab4615db:
src/Makefile: use VERSION variable consistently (2021-11-15 13:09:30 +0000)
Bikal Lem (1):
src/Makefile: use VERSION variable consistently
Makefile        | 6 ++----
Makefile.common | 5 +++++
liburing.spec   | 2 +-
src/Makefile    | 8 ++++----
4 files changed, 12 insertions(+), 9 deletions(-)
create mode 100644 Makefile.common
```

[GIT PULL] src/Makefile: use VERSION variable consistently

---

examples/link-cp.c

The last file-block size may less than BS(32*1024), the failure retry may overflow.

examples/link-cp.c: fix the last file-block retry may overflow

---

configure
test/Makefile

Update configure and test/Makefile, such that if !CONFIG_HAVE_STATX will
not generate statx.c test. Without this patch, liburing fails to compile
on an older toolchain that does not have statx available.
Fixes: #516
Signed-off-by: Jon Kohler <jon@nutanix.com>

[GIT PULL] configure: fix statx configure and build on !CONFIG_HAVE_STATX toolchains

---

src/arch/x86/syscall.h

The current wrapper uses `__do_syscall2` (wrong arity, should be 3) and ignores the `advice` parameter.
----
```
The following changes since commit fd1d6cfafb4e9fb4d826175247527c7d1ca4ffc1:
test/pollfree: use mmap(2) instead of a manual syscall (2022-02-21 05:11:29 -0700)
https://github.com/Spasi/liburing.git fix_madvise_syscall
for you to fetch changes up to e05652f22ee5b5bcc78f69a09ed7a7ba883a928a:
Fix madvise syscall wrapper (2022-02-21 15:33:09 +0200)
Ioannis Tsakpinis (1):
Fix madvise syscall wrapper
src/arch/x86/syscall.h | 2 +-
```
----
<details>
1. To make everyone easily …

[GIT PULL] Fix madvise syscall wrapper

---

.github/workflows/build.yml

Hi Jens,
Please pull 1 commit for the GitHub bot.
```
The following changes since commit 63dc2177ed42fd0ae45cb66e169a28305e0fe622:
test/pollfree: fix compile on 32-bit x86 (2022-02-21 10:24:17 -0700)
git://github.com/ammarfaizi2/liburing.git tags/multiarch-gh-ci-20220222
for you to fetch changes up to f1e75bed0a508177225e3c0fad037a6f1154f53f:
.github/workflows: Add multiarch GitHub CI build support (2022-02-22 18:09:57 +0700)
multiarch-gh-ci-20220222
This adds multiarch build for GitHub bot. Currently, only GCC that
supports multiarch build. I couldn't find the clang cross compiler
package from the Ubuntu apt, so let's skip it at the moment.
New arch(s) build support:
- aarch64
- arm …
```

[GIT PULL] Add multiarch GitHub CI build support

---

configure

Hi Jens,
Two configure script fixes from Alviro:
- configure: Fix _GNU_SOURCE redefinition warning
- configure: Fix clang-12 warning `-Wdeprecated`
Please pull!
```
The following changes since commit 93e30695bb0c4e27bd2ab9a7e91a8279225d1264:
Merge tag 'multiarch-gh-ci-20220222' of https://github.com/ammarfaizi2/liburing (2022-02-22 06:14:09 -0700)
https://github.com/ammarfaizi2/liburing tags/liburing-2022-02-23
for you to fetch changes up to 2cd9452658b6420e0211ed0a0e1440bed50bdbf7:
configure: Fix clang-12 warning `-Wdeprecated` (2022-02-23 11:46:05 +0700)
liburing-2022-02-23
Two configure script fixes from Alviro Iskandar Setiawan:
- configure: Fix _GNU_SOURCE redefinition warning
- …
```

[GIT PULL] configure script fixes

---

src/include/liburing/barrier.h
src/queue.c

A full memory barrier is required between the store to the SQ tail in
__io_uring_flush_sq and the load of the flags in sq_ring_needs_enter
to prevent a situation where the kernel thread goes to sleep while
sq_ring_needs_enter returns false
Fixes: https://github.com/axboe/liburing/issues/541
Signed-off-by: Almog Khaikin <almogkh@gmail.com>
----
```
The following changes since commit 2de98320d5b02951936fc0ab677dd01e4fb2a7a7:
src/Makefile: Don't use stack protector for all builds by default (2022-02-25 07:17:37 -0700)
https://github.com/almogkh/liburing fix-needenter
for you to fetch changes up to 748fd137c7f70d352fdc546535cf52108352e827:
Fix memory ordering in sq_ring_needs_enter (2022-03-05 19:18:24 +0200) …
```

[GIT PULL] Fix memory ordering in sq_ring_needs_enter

---

Makefile

prefix suffice for setting *dir variables in src/Makefile; this does
away with setting does in in ./Makefile
----
```
The following changes since commit 6231f56da7881bde6fb011e1b54d672f8fe5a224:
src/queue: don't keep looping for IOPOLL peek operation (2022-03-05 15:47:26 -0700)
https://github.com/257/liburing.git makefile
for you to fetch changes up to c1f157802c72e8a331710e675e843e6aa4c2c7ad:
[GIT PULL] make: let src/Makefile set *dir vars properly (2022-03-09 15:51:31 -0500)
Paymon MARANDI (1):
[GIT PULL] make: let src/Makefile set *dir vars properly
Makefile | 6 +-----
1 file changed, 1 insertion(+), 5 deletions(-)
```
----
<details> …

make: let src/Makefile set *dir vars properly

---

configure

Hi Jens,
One configure script fix for liburing:
- Allow the configure script to fail with a non-zero exit code.
Please pull!
Cc: @romange 
```
The following changes since commit 3b52ae980c41b420592e3005199041890a56d6dc:
test/fixed-reuse: test that linked file slot reuse is correct (2022-03-30 11:33:38 -0600)
https://github.com/ammarfaizi2/liburing tags/liburing-2022-05-01
for you to fetch changes up to 30830bddbfbe9503836bdcb3ed90ec3f945d122d:
configure: Allow the configure script to fail with a non-zero exit code (2022-04-01 23:23:02 +0700)
Pull a configure script fix from Ammar Faizi:
- Allow the configure script to fail with a non-zero exit code.
Link: …
```

[GIT PULL] configure: Allow the configure script to fail with a non-zero exit code

---

test/recv-msgall-stream.c
test/recv-msgall.c
test/send_recv.c
test/send_recvmsg.c

Remove "obviously useless" double casts.
----
```
The following changes since commit 000dd873f4da9b6052792c93d4d0978bb4ea3252:
test/open-direct-link: add IOSQE_ASYNC (2022-03-29 16:38:27 -0600)
dankamongmen remove-double-cast
for you to fetch changes up to 662989e4aa2cac1d6f87b3ada5c1fd579d5d75b3:
remove double casts (2022-04-04 10:57:27 -0400)
nick black (1):
remove double casts
test/recv-msgall-stream.c | 2 +-
test/recv-msgall.c        | 2 +-
test/send_recv.c          | 2 +-
test/send_recvmsg.c       | 2 +-
4 files changed, 4 insertions(+), 4 deletions(-)
```
----
<details>
1. To make everyone easily filter pull request …

[GIT PULL] remove double casts

---

man/io_uring.7
man/io_uring_cq_advance.3
man/io_uring_cqe_seen.3
man/io_uring_opcode_supported.3
man/io_uring_peek_cqe.3
man/io_uring_prep_accept.3
man/io_uring_prep_files_update.3
man/io_uring_prep_msg_ring.3
man/io_uring_prep_provide_buffers.3
man/io_uring_prep_read_fixed.3
man/io_uring_prep_splice.3
man/io_uring_prep_tee.3
man/io_uring_prep_timeout.3
man/io_uring_prep_timeout_update.3
man/io_uring_prep_write.3
man/io_uring_prep_write_fixed.3
man/io_uring_prep_writev.3
man/io_uring_prep_writev2.3
man/io_uring_queue_init.3
man/io_uring_register_buffers.3
man/io_uring_sqe_set_flags.3
man/io_uring_submit_and_wait_timeout.3

- Use of "consumed" vs "processed" was inconsistent - "consumed" was
more common, so I changed the few instances of "processed" to that. It
was non-obvious to me if consumption was different from processing, so
this removes that ambiguity.
- Fixed a few comma splices and typos in both function names and
descriptions.
Signed-off-by: Eric Wyler <ewyler@gmail.com>
----
```
The following changes since commit 215c27ac35d334d6be9c8982b52faf97ff78c26f:
Merge branch 'dankamongmen/remove-double-cast' of https://github.com/dankamongmen/liburing (2022-04-04 09:02:32 -0600)
https://github.com/ewyler/liburing changes-3
for you to fetch changes up to 30a3c697057e4457aadbd71b282b21a39f578bbd:
Review and update .3 and .7 man pages (2022-04-04 16:21:36 -0400) …
```

[GIT PULL] Review and update .3 and .7 man pages

---

test/35fa71a030ca.c
test/rw_merge_test.c
test/submit-reuse.c

Hi Jens,
- Two fixes for `-Wunused-but-set-variable` warning from clang-15.
- Fix the wrong assertion condition and testfile cleanup in
test/submit_reuse.
Please pull!
```
The following changes since commit 7cea31e742c175b8df2895b57f472b49ff514ee0:
man/io_uring_setup.2: document recent FEAT flag additions (2022-04-14 11:22:51 -0600)
https://github.com/ammarfaizi2/liburing tags/test-fixes-2022-04-15
for you to fetch changes up to 045b8c5b183859fbc481ec7ab6b818442cc57ab0:
test/submit-reuse: Fix `-Wunused-but-set-variable` warning from clang-15 (2022-04-15 04:24:24 +0700)
Pull test fixes from Ammar Faizi:
- Two fixes for `-Wunused-but-set-variable` warning from clang-15.
- Fix the wrong …
```

[GIT PULL] Test fixes

---

configure

This is related to the the issue reported here: https://github.com/axboe/liburing/issues/578
A fix for the reported issue changed ``linux/stat.h`` to ``sys/stat.h`` , however, it did not change the compile-check in ``configure``. 
This commit is needed on Alpine Linux / muslc, where 'statx' is detected by ``configure/compile-check`` but ``sys/stat.h`` does not provide what is needed by ``test/statx.c``. Resulting in a build-error.
This changes the compiler-check to match the usage in `tests/statx.c`, thereby fixing the build-error on Alpine Linux / muslc.
----
```
The following changes since commit b2d28aea257d0eee40bcdc5c0613712c9e4e8184:
io_uring.h: sync with 5.19 io_uring release (2022-05-17 06:04:15 -0600)
https://github.com/safl/liburing.git …
```

[GIT PULL] configure: fix compile-checks for statx

---

.github/workflows/build.yml

Hi Jens,
GitHub bot updates this time:
- Use clang latest version for better issue coverage.
- Add more architectures for GitHub bot: powerpc64, powerpc, alpha,
mips64, mips.
Please pull!
```
The following changes since commit a12f209d0133b71648da3f0d7d71997b35f75359:
test/socket: fix argument order for socket prep (2022-06-01 08:16:08 -0600)
https://github.com/ammarfaizi2/liburing tags/github-bot-2022-06-02
for you to fetch changes up to df9874a6ff66bd22edf99b558e78af0ddfa999ed:
.github: Add mips build for GitHub bot (2022-06-02 08:10:21 +0700)
Pull GitHub bot updates from Ammar Faizi:
- Use clang latest version for better issue coverage.
- Add more architectures for GitHub bot: …
```

[GIT PULL] GitHub bot updates

---

man/io_uring_prep_accept.3

`io_uring_prep_accept` and its variants accept `socklen_t *` not
`socklen_t`.
Signed-off-by: Seiichi Uchida <topecongiro@fastmail.com>
----
```
The following changes since commit a7fb522e3b03b6ecc53355305a587164dbec2df8:
cHANGELOG: add a few more updates (2022-06-04 06:07:36 -0600)
https://github.com/topecongiro/liburing fix/man-accept
for you to fetch changes up to 1f4041a064df14e1bdfd7b7a540b64ea7e85d1fb:
man/io_uring_prep_accept.3: fix parameter types (2022-06-06 10:00:37 +0900)
Seiichi Uchida (1):
man/io_uring_prep_accept.3: fix parameter types
man/io_uring_prep_accept.3 | 8 ++++----
1 file changed, 4 insertions(+), 4 deletions(-)
```

[GIT PULL] man/io_uring_prep_accept.3: fix parameter types

---

CHANGELOG

During reading the recently added CHANGELOG I stumbled over
IORING_SETUP_COOP_TASKRUN which is documented in man/io_uring_setup.2
rather than in man/io_uring_enter.3.
Fixes: b7911762 ("Add CHANGELOG file")
Signed-off-by: Florian Fischer <florian.fischer@muhq.space>
----
```
The following changes since commit 807c8169e153a3985f1a4deddc302846673ef979:
Merge branch 'fix/man-madvise' of https://github.com/topecongiro/liburing (2022-06-07 00:42:16 -0600)
https://github.com/fischerling/liburing/ fix-changelog-man-reference
for you to fetch changes up to ed447b9aa0d84aaf5402021c68cba3d62c3d7a37:
changelog: fix wrong man page reference (2022-06-13 14:16:34 +0200)
Florian Fischer (1): …
```

changelog: fix wrong man page reference

---

man/io_uring_enter.2

Fix typo in the manual for `io_uring_enter`.

man: fix typo in manual for io_uring_enter

---

man/io_uring.7
man/io_uring_cq_ready.3
man/io_uring_enter.2
man/io_uring_free_probe.3
man/io_uring_get_probe.3
man/io_uring_opcode_supported.3
man/io_uring_prep_read_fixed.3
man/io_uring_prep_write_fixed.3
man/io_uring_register.2
man/io_uring_register_buf_ring.3
man/io_uring_setup.2
man/io_uring_sq_ready.3
man/io_uring_sq_space_left.3
man/io_uring_sqe_set_flags.3
man/io_uring_sqring_wait.3
man/io_uring_wait_cqe.3
man/io_uring_wait_cqe_nr.3
man/io_uring_wait_cqe_timeout.3
man/io_uring_wait_cqes.3
test/fixed-link.c
test/multicqes_drain.c
test/rsrc_tags.c
test/rw_merge_test.c
test/single-issuer.c
test/timeout.c

Several typo and man page fixes.
----
```
The following changes since commit bf3fedba890e66d644692910964fe1d8cbf4fb1b:
test/xattr: don't rely on NUL-termination (2022-08-16 06:23:05 -0600)
https://github.com/guillemj/liburing pu/man-fixes
for you to fetch changes up to bf46399506adb26465f0da065b32d4318f9e7e68:
man: Lowercase man page name in title header (2022-08-16 21:21:25 +0200)
Guillem Jover (7):
Fix typo for "cancellation"
Fix typo for "returns"
Fix typo for "suppression"
Fix typo for "successfully"
Fix typo for "or"
man: Add missing section numbers
man: Lowercase man page name in title header
CHANGELOG                       |  2 +-
man/io_uring.7                  |  2 +- …
```

Typos and man page fixes

---

src/include/liburing.h
src/queue.c
src/setup.c
test/accept-reuse.c
test/accept.c
test/io_uring_enter.c

Avoid an additional pointer indirection to `ring_mask` and `ring_entries`,
since their values can't change after the ring is created.
The fields `kring_mask` and `kring_entries` are no longer needed,
but kept for backwards compatibility since `liburing.h` exposes them.
They can be removed in a future major release, saving 8 bytes per queue.
----
```
The following changes since commit 8af924d6d3ac6a92c4af1df847cf713e4d2b67e3:
liburing: fix return code for test/hardlink.t (2022-08-26 12:42:25 -0600)
git@github.com:calebsander/liburing.git refactor/cache-ring-size
for you to fetch changes up to f5cd4eb2b50840510a4c6bbe5ba34a5a2058a2ae:
liburing: cache ring sizes and masks (2022-08-28 13:24:23 -0600) …
```

[GIT PULL] liburing: cache ring sizes and masks

---

src/queue.c
test/io_uring_passthrough.c
test/iopoll.c

This function can't fail and returns a count of SQEs ready to submit.
Most callers implicitly cast the return value to `unsigned` anyways:
- `__io_uring_submit_timeout()` returns it as an `int`, since it can fail
- `io_uring_submit_and_wait_timeout()` stores it in an `unsigned` field
or passes it as an `unsigned` parameter
- `__io_uring_submit_and_wait()` passes it as an `unsigned` parameter
- The tests pass it as an `unsigned` parameter
----
```
The following changes since commit b1486931117f643b0ad6612beb3f9563b508126c:
Merge branch 'refactor/cache-ring-size' of https://github.com/calebsander/liburing (2022-08-28 14:06:55 -0600)
git@github.com:calebsander/liburing.git fix/flush-sq-unsigned
for you to fetch changes up to …
```

queue: return unsigned from __io_uring_flush_sq()

---

src/queue.c
src/setup.c

`_io_uring_get_sqe()` assumes SQ and SQE indices are interchangeable,
as it checks whether `sqe_tail - sq_head <= ring_entries`.
Under this assumption, we can set the SQ array during initialization
instead of every time SQEs are submitted.
We can also avoid dereferencing `ktail`, since `*ktail == sqe_head`.
----
```
The following changes since commit bf248850dc2ae45d29d4fdde688e90d24f3dd6d2:
Merge branch 'fix/flush-sq-unsigned' of https://github.com/calebsander/liburing (2022-08-28 19:27:44 -0600)
git@github.com:calebsander/liburing.git refactor/sq-init
for you to fetch changes up to c65a873711d74d521f24a914d23653985bc7fa6d:
queue: assume direct SQ-SQE mapping (2022-08-29 11:07:00 -0600)
--------------------------------------------------------------- …
```

[GIT PULL] queue: assume direct SQ-SQE mapping

---

src/queue.c

Even when not submitting SQEs, `io_uring_enter()`
may be needed for IOPOLL mode or if the CQ overflowed.
Let `io_uring_submit()` still make the syscall in this case.
Fixes: 504efe18c213 ("queue: avoid io_uring_enter() with no SQEs")
----
```
The following changes since commit 243477691678af27dafe378f1e19be5df61e9daf:
Revert "src/queue: always enter for IOPOLL" (2022-08-29 15:10:15 -0600)
git@github.com:calebsander/liburing.git fix/iopoll-submit
for you to fetch changes up to e5297de76bdb1d3593ff947b0100eead52c9b148:
queue: enter if CQ needs it, even if SQ doesn't (2022-08-29 18:21:57 -0600)
Caleb Sander (1):
queue: enter if CQ needs it, even if SQ doesn't
src/queue.c | 5 +++--
1 file …
```

[GIT PULL] queue: enter if CQ needs it, even if SQ doesn't

---

src/include/liburing.h

The system calls `getxattr` and `fgetxattr` return data in the pointer passed as `value`, as is clearly layed out in the [man page](https://man7.org/linux/man-pages/man2/getxattr.2.html) for the actual syscalls.
----
```
The following changes since commit a71d56ef3259216739677473ddb17ad861c3a964:
queue: Remove unnecessary goto and label (2022-08-30 19:00:13 -0600)
https://github.com/Thalhammer/liburing patch-1
for you to fetch changes up to c9906af5dd00210fc31cf867bb7c4dd0ce08ba9a:
Fix constant correctness error in `getxattr`/`fgetxattr` (2022-09-01 13:19:45 +0200)
Dominik Thalhammer (1):
Fix constant correctness error in `getxattr`/`fgetxattr`
src/include/liburing.h | 4 ++--
1 file …
```

[GIT PULL] Fix constant correctness error in `getxattr`/`fgetxattr`

---

src/include/liburing.h
src/register.c

`io_uring_register_files_update` took a pointer to a mutable integer array despite neither liburing nor the kernel modifying it.
----
```
The following changes since commit 860db521db4c86a1cb5d0b672a8fba83a89f01f0:
examples: adjust zc bench to the new uapi (2022-09-02 05:56:53 -0600)
https://github.com/Thalhammer/liburing patch-2
for you to fetch changes up to 2b2a26d8ba1db96fcff4a824400bf214029d36b7:
Fix constant correctness error in `io_uring_register_files_update` (2022-09-03 13:42:33 +0200)
Dominik Thalhammer (1):
Fix constant correctness error in `io_uring_register_files_update`
src/include/liburing.h | 2 +-
src/register.c         | 2 +-
2 files changed, 2 insertions(+), 2 …
```

[GIT PULL] Fix constant correctness error in `io_uring_register_files_update`

---

test/sigfd-deadlock.c

A couple of minor changes for `test/sigfd-deadlock`:
- check for `-errno` before flagging success on `(cqe->res & POLLIN)`
- skip on `-EOPNOTSUPP` poll error; it may be returned by Stable kernels carrying
`fc78b2fc21f1 ("io_uring: disable polling pollfree files")`
- use `enum t_test_result` values
----
```
The following changes since commit 1cba5d6c9e41e2f55ac4c3f93f5e05f9b5082a3e:
tests: test async_data double-free with sendzc (2022-09-26 08:33:49 -0600)
https://github.com/ddiss/liburing test-sigfd-deadlock
for you to fetch changes up to 29ad0c893d5b1f79cff2e0ebe18fd887eface63c:
test/sigfd-deadlock: skip test if poll returns -EOPNOTSUPP (2022-09-27 20:02:27 +0200)
David Disseldorp …
```

[GIT PULL] test/sigfd-deadlock: improve error handling

---

man/io_uring_register_sync_cancel.3

The SYNOPSIS of `io_uring_register_sync_cancel` was originally `int io_uring_register_buffers(...)` but now it has been corrected.
----
```
The following changes since commit 82a4dfc212478935f81f0f385da01458e8d5d7ec:
liburing: add more zc helpers (2022-09-28 07:53:52 -0600)
https://github.com/Codesire-Deng/liburing master
for you to fetch changes up to b6b17b5436de673731e2dcfa036290536d543125:
man: fix SYNOPSIS of `io_uring_register_sync_cancel` (2022-09-29 18:22:54 +0800)
Zifeng Deng (1):
man: fix SYNOPSIS of `io_uring_register_sync_cancel`
man/io_uring_register_sync_cancel.3 | 2 +-
```
----
1. I have followed the above pull request …

[GIT PULL] man: fix SYNOPSIS of `io_uring_register_sync_cancel`

---

man/io_uring_enter.2
man/io_uring_prep_read.3
man/io_uring_prep_readv.3
man/io_uring_prep_readv2.3
man/io_uring_prep_write.3
man/io_uring_prep_writev.3
man/io_uring_prep_writev2.3

I'd like to use io_uring with a mix of seekable and non-seekable files and it isn't clear from the docs how to do that safely. This is a proposal to tweak the API contract a bit towards that end. Thanks.
----
```
The following changes since commit af3da48f6387fcd530177a3ecfc04c4d5e5698d8:
man/io_uring_register_sync_cancel.3: line up 2nd line properly (2022-09-29 07:17:35 -0600)
https://github.com/fkm3/liburing.git clarify_seekable
for you to fetch changes up to 3efaca5ea0b27b07de01ae84365ed96df3b4c2f9:
man: clarify non-seekable file read/write API (2022-09-30 01:14:40 +0000)
Frederick Mayle (1):
man: clarify non-seekable file read/write API
man/io_uring_enter.2        | 4 ++-- …
```

[GIT PULL] man: clarify non-seekable file read/write API

---

man/io_uring_buf_ring_advance.3
man/io_uring_buf_ring_cq_advance.3
test/helpers.h

Hi Jens,
- Fix the wrong return type in io_uring_buf_ring_advance
and io_uring_buf_ring_cq_advance man page (Alviro)
- Clean up a build warning when compiling with clang v13.0.1 (me)
Please pull!
```
The following changes since commit 409ad09c69a003a4cc69f690155023ecec9999b7:
Merge branch 'master' of https://github.com/ilikdoge/liburing (2022-10-17 15:57:12 -0700)
https://github.com/ammarfaizi2/liburing tags/liburing-fixes-2022-10-19
for you to fetch changes up to 877d41862ac111fdd85344804c4d656ac7267c93:
test/helpers: Fix clang warning (2022-10-19 04:46:03 +0700)
liburing-fixes-2022-10-19
Alviro Iskandar Setiawan (2): …
```

[GIT PULL] man page and build warning fixes

---

src/include/liburing/io_uring.h

Fixes: https://github.com/axboe/liburing/issues/708

uapi: Sync with the kernel in order to build systems without linux/time_types.h

---

.gitignore
Makefile.common
configure
man/IO_URING_CHECK_VERSION.3
man/IO_URING_VERSION_MAJOR.3
man/IO_URING_VERSION_MINOR.3
man/io_uring_check_version.3
man/io_uring_major_version.3
man/io_uring_minor_version.3
src/Makefile
src/include/liburing.h
src/liburing.map
src/version.c
test/Makefile
test/version.c

Pretty standard API additions for shared library version checking at both compile-time and run-time.
Adds the following to the ABI for runtime checks:
```
int io_uring_major_version (void);
int io_uring_minor_verison (void);
bool io_uring_check_version(int major, int minor);
```
Adds the following to the API for compile time checks:
```
#define IO_URING_CHECK_VERSION(major,minor) ...
#define IO_URING_VERSION_MAJOR ...
#define IO_URING_VERSION_MINOR ...
```
A new `io_uring_version.h` header is installed next to `compat.h` and generated similarly in `configure`.
Includes some basic tests as well.
The only sort of "wizardry" here is that we use a not-so-common trick to parse `Makefile.common` with `make` to extract the values of `$VERSION_MAJOR` and `$VERSION_MINOR`. (I've been doing this in …

[GIT PULL] Add compile-time and run-time version check API

---

man/io_uring_prep_provide_buffers.3

Fixed the parameters description.
Fixed the return value description. Kernel is inconsistent here depending on its version and if the group is created or updated. I'm guessing the manual is not just for the latest version, so changed the description to be more general.
Removed EBADF as there are no fds used.
----
```
The following changes since commit 59c7e39d3584f4d3615f366664a0fb1c32d00354:
Merge branch 'master' of https://github.com/chergert/liburing (2022-12-01 12:36:38 -0700)
https://github.com/wlukowicz/liburing.git provide-buffers-man-fixes
for you to fetch changes up to 55a3e6ac0f9874739de28db9723ba747039e7980:
man/io_uring_prep_provide_buffers.3: several fixes (2022-12-03 13:53:59 +0000) …
```

[GIT PULL] man/io_uring_prep_provide_buffers.3: several fixes

---

man/io_uring_prep_readv.3
man/io_uring_prep_readv2.3
man/io_uring_setup.2

The readv and readv2 man pages have a typo that probably came from the write man page.
I also want to update the example for handling IORING_SQ_NEED_WAKEUP in the io_uring_setup man page.
These changes fixes 2 small typos on io_uring_prep_readv, io_uring_prep_readv2 man pages and tries to clarify the polling example in the io_uring_setup man page.
----
```
The following changes since commit 5772879454421e82ae153c60853cf378a314e8f9:
Merge branch 'provide-buffers-man-fixes' of https://github.com/wlukowicz/liburing (2022-12-03 09:27:37 -0700)
git@github.com:bignacio/liburing.git issue_746_man-page-fixes-improvements
for you to fetch changes up to 0228709ca2ea662c85a154e646c16f869fadbc50:
fix documentation for readv, readv2 and setup (2022-12-04 …
```

[GIT PULL] fix: documentation for readv, readv2 and setup

---

man/io_uring_prep_msg_ring.3

The current message for io_uring_prep_msg_ring(3) is a bit confusing. Removing the additional 'a' char makes the reading smoother.
Signed-off-by: Breno Leitao <leitao@debian.org>
----
```
The following changes since commit f6d880f0c9be588cc71007d9c36d1160fe8ab54e:
test: always use local liburing.h header (2023-01-03 15:24:03 -0700)
git@github.com:leitao/liburing.git upstream
for you to fetch changes up to 66a61b526fd7a1a76bdfa9a906b06d88f0fe6246:
man/io_uring_prep_msg_ring.3: Remove an extra char (2023-01-04 03:16:19 -0800)
Breno Leitao (1):
man/io_uring_prep_msg_ring.3: Remove an extra char
man/io_uring_prep_msg_ring.3 | 2 +-
```

[GIT PULL] man/io_uring_prep_msg_ring.3: Remove an extra char

---

src/include/liburing.h

io_uring_prep_msg_ring(3) is setting sqe->rw_flags for the flags. Since this is a message ring operation, let's use the proper field, msg_ring_flags.
Discussion at https://github.com/axboe/liburing/pull/765#discussion_r1061346797
Signed-off-by: Breno Leitao <leitao@debian.org>
----
```
The following changes since commit f5a48392c4ea33f222cbebeb2e2fc31620162949:
Merge branch 'man-fixes' of https://github.com/wlukowicz/liburing (2023-01-08 09:45:24 -0700)
git@github.com:leitao/liburing.git upstream
for you to fetch changes up to 59bb5b8660186589c15104ab78626d14656dde4a:
liburing.h: Use proper sqe flags (2023-01-09 09:34:55 -0800)
Breno Leitao (1):
liburing.h: Use proper sqe flags …
```

liburing.h: Use proper sqe flags

---

CHANGELOG
man/io_uring_prep_msg_ring.3
man/io_uring_prep_msg_ring_cqe_flags.3
src/include/liburing.h
src/include/liburing/io_uring.h
test/Makefile
test/msg-ring-flags.c

This PR adds support for a new flag to pass through flags from SQE to CQE. 
Basically, you specify the flags you want to see in `cqe->flags` by setting `sqe->file_index`, and toggling the new flag `IORING_MSG_RING_FLAGS_PASS` 
Kernel patch: https://lore.kernel.org/io-uring/20230103160507.617416-1-leitao@debian.org/T/#u
----
```
The following changes since commit 052c2e03e4b64e07f9d4e43ed816cd8e5721b9d8:
Merge branch 'io_uring_uapi' of https://github.com/metze-samba/liburing (2022-12-28 10:04:10 -0700)
git@github.com:leitao/liburing.git master
for you to fetch changes up to f08da78a3b0ff6c175bbaeb8ddd35cb11a1635d8:
test/io_uring_prep_msg_ring_cqe_flags new test (2023-01-03 06:51:17 -0800)
--------------------------------------------------------------- …
```

[GIT PULL] Add support for io_uring_prep_msg_ring_cqe_flags(3)

---

man/io_uring_prep_accept.3
man/io_uring_setup.2

Fix one typo in wording and another in a troff macro.
Warned-by: lintian
Signed-off-by: Guillem Jover <guillem@hadrons.org>
----
```
The following changes since commit 849f5ba89b0d1ccf9d825160bf8560ad9901c48b:
tests: lazy pollwq activation for disabled rings (2023-01-16 10:48:45 -0700)
https://github.com/guillemj/liburing pu/man-fixes
for you to fetch changes up to 4215200cf419f7d85cefa04b11a8258d4c8f4974:
man: Fix typos (2023-01-18 02:53:30 +0100)
Guillem Jover (1):
man: Fix typos
man/io_uring_prep_accept.3 | 2 +-
man/io_uring_setup.2       | 2 +-
2 files changed, 2 insertions(+), 2 deletions(-)
```
----
<details>
1. To …

[GIT PULL] man: Fix typos

---

man/io_uring_prep_fgetxattr.3
man/io_uring_prep_fsetxattr.3
man/io_uring_prep_getxattr.3
man/io_uring_prep_link_timeout.3
man/io_uring_prep_send_set_addr.3
man/io_uring_prep_send_zc.3
man/io_uring_prep_send_zc_fixed.3
man/io_uring_prep_sendmsg.3
man/io_uring_prep_sendmsg_zc.3
man/io_uring_prep_setxattr.3

Adds man pages for following prep functions (part of https://github.com/axboe/liburing/issues/777):
-  io_uring_prep_link_timeout
-  io_uring_prep_send_zc_fixed
-  io_uring_prep_sendmsg_zc
-  io_uring_prep_send_set_addr
-  io_uring_prep_getxattr
-  io_uring_prep_setxattr
-  io_uring_prep_fgetxattr
-  io_uring_prep_fsetxattr

Add prep functions man pages

---

configure

When I ran `build-debs.sh` on my Debian 11 system, I got a bunch of errors because the generated `io_uring_version.h` contained:
```
/* SPDX-License-Identifier: MIT */
#ifndef LIBURING_VERSION_H
#define LIBURING_VERSION_H
#define IO_URING_VERSION_MAJOR make[2]: Entering directory '/tmp/release/Debian/liburing/liburing-2.3'
2
make[2]: Leaving directory '/tmp/release/Debian/liburing/liburing-2.3'
#define IO_URING_VERSION_MINOR make[2]: Entering directory '/tmp/release/Debian/liburing/liburing-2.3'
4
make[2]: Leaving directory '/tmp/release/Debian/liburing/liburing-2.3'
#endif
```
The "Entering directory" and "Leaving directory" are generated by make called by configure with these 3 lines:
```
MAKE_PRINT_VARS="include Makefile.common\nprint-%: ; @echo \$(\$*)\n"
VERSION_MAJOR=$(env echo -e …
```

use make --no-print-directory to generate version string

---

examples/send-zerocopy.c
test/defer-taskrun.c
test/helpers.c
test/helpers.h
test/poll.c
test/send-zerocopy.c
test/single-issuer.c

On musl systems, liburing cannot build examples and tests due to it's usage of error.h. Replace all calls to error() with fprintf(stderr, ...) and exit(1).
Closes: #786
Signed-off-by: Steffen Winter <steffen.winter@proton.me>

Remove calls to error() from error.h.

---

test/eventfd-ring.c
test/eventfd.c
test/rename.c
test/unlink.c

Several tests used the copy-pasted description "run various nop tests".
Change them to have appropriate descriptions.
Signed-off-by: Josh Triplett <josh@joshtriplett.org>
----
```
The following changes since commit b435c899974fdc14725f83a7b4a72658d9dc65e0:
test/lfs-openat*: use O_LARGEFILE to open the file (2023-02-15 14:29:22 -0700)
https://github.com/joshtriplett/liburing test-description-typo
for you to fetch changes up to 16d0b1a8faf78239adfd31b1a82709aac0467095:
Fix some copy-paste errors in test descriptions (2023-02-15 21:28:31 -0800)
Josh Triplett (1):
Fix some copy-paste errors in test descriptions
test/eventfd-ring.c | 2 +-
test/eventfd.c      | 2 +-
test/rename.c       | 2 …
```

[GIT PULL] Fix some copy-paste errors in test descriptions

---

.gitignore
CHANGELOG
examples/Makefile
examples/io_uring-close-test.c
man/io_uring_close_ring_fd.3
man/io_uring_register.2
man/io_uring_setup.2
src/include/liburing.h
src/include/liburing/io_uring.h
src/int_flags.h
src/liburing-ffi.map
src/liburing.map
src/register.c
src/setup.c
test/Makefile
test/reg-reg-ring.c

This provides the userspace corresponding to the kernel patch at
https://lore.kernel.org/io-uring/3cbedc531b633af4fe8632f7276aa843b5a54875.1664123680.git.josh@joshtriplett.org/T/
.
With this change, a caller of liburing can handle a ring internally without
leaving a file descriptor open that might disrupt its caller, which makes it
safer to retrofit existing libraries with strict compatibility requirements to
use `io_uring`.
Libraries with even more stringent requirements (e.g. never even transiently
having a file descriptor open) will need two additional pieces:
- Adding a flag to `io_uring_setup` to set up the ring directly as a registered
file descriptor, without ever putting it in the file descriptor table.
- Supporting the initial `mmap` via a registered file descriptor, such as via …

[GIT PULL] Support using a ring exclusively via registered index

---

man/io_uring_register_buffers.3
man/io_uring_register_buffers_sparse.3
man/io_uring_register_buffers_tags.3
man/io_uring_register_buffers_update_tag.3
man/io_uring_register_files.3
man/io_uring_register_files_tags.3
man/io_uring_register_files_update.3
man/io_uring_register_files_update_tag.3

Adds man pages for following register functions (part of https://github.com/axboe/liburing/issues/777):
- io_uring_register_buffers_sparse
- io_uring_register_buffers_update_tag
- io_uring_register_buffers_tags
- io_uring_register_files_tags
- io_uring_register_files_update
- io_uring_register_files_update_tag

Add register functions man pages (buffers and files)

---

man/io_uring_buf_ring_cq_advance.3

Correct word spelling for `io_uring_buf_ring_cq_advance.3` man page.
----
```
The following changes since commit 9e4190aed43f25b2986155a2f6019fc2fc89920f:
man/io_uring_register_{buffers,files}: Kill trailing whitespaces (2023-03-07 13:54:54 -0700)
https://github.com/chimaoshu/liburing master
for you to fetch changes up to a3a8289665437e9ac741439155baf72f402692d5:
[GIT PULL] man/io_uring_buf_ring_cq_advance.3: correct word spelling (2023-03-10 00:09:30 +0800)
chimaoshu (1):
[GIT PULL] man/io_uring_buf_ring_cq_advance.3: correct word spelling
man/io_uring_buf_ring_cq_advance.3 | 2 +-
```
----
<details> …

[GIT PULL] man/io_uring_buf_ring_cq_advance.3: correct word spelling

---

man/io_uring_register.2
man/io_uring_setup.2

This PR adds some documentation that shutdown processing after closing the io_uring file descriptor runs asynchronously.
This does not matter in most cases, but can lead to unexpected behavior if users previously registered some buffers that they did not explicitly unregister. In this case the pinned pages have not necessarily been unpinned yet when the close call returns, and subsequently setting up another io_uring instance with registered buffers may fail when running with a tight RLIMIT_MEMLOCK limit.
----
```
The following changes since commit 0c020c66a413980e237a22f8620fa8e22150a6b5:
man/io_uring_prep_timeout_update: add note that remove doesn't take flags (2023-03-25 07:55:37 -0600)
git@github.com:freitmi/liburing.git 
for you to fetch …
```

[GIT PULL] document that shutdown processing may run asynchronously

---

man/io_uring.7
man/io_uring_queue_init.3
man/io_uring_setup.2

The inline examples currently reference atomic_store_release(),
though io_uring_smp_store_release() in the standalone example
uses C11's atomic_store_explicit(). Use atomic_store_explicit()
in the standalone example together with memory_order_release.
----
```
The following changes since commit 000dd873f4da9b6052792c93d4d0978bb4ea3252:
test/open-direct-link: add IOSQE_ASYNC (2022-03-29 16:38:27 -0600)
https://github.com/dankamongmen/liburing.git dankamongmen/man-atomics
for you to fetch changes up to 94ed3b286e00fe4fdc1f97633e10934896aa9a77:
io_uring.7: atomic_store_explicit() in examples (2022-04-02 02:04:52 -0400)
nick black (1):
io_uring.7: atomic_store_explicit() in examples …
```

[GIT PULL] io_uring.7: atomic_store_explicit() in examples

---

man/io_uring_cqe_seen.3
man/io_uring_enter.2
man/io_uring_wait_cqe.3
man/io_uring_wait_cqe_timeout.3

io_uring_cqe_seen.3 and io_uring_wait_cqe_timeout.3 linked to themselves, while the latter was missing a link to io_uring_wait_cqes. the three waits now refer to the other two waits, seen links to all three waits, and none of them link to themselves.
also, fix an instance of "io_uring_getevents_args" to refer properly to io_uring_getevents_arg.
----
```
The following changes since commit e02de6202ecb77b50c283993f82eea257a4fb50d:
Merge branch 'dankamongmen/man-atomics' of https://github.com/dankamongmen/liburing (2023-05-13 19:40:49 -0600)
https://github.com/dankamongmen/liburing/ dankamongmen/io_uring_getevent_arghhhhh
for you to fetch changes up to 5dffb61d4d61c7813a8043ee9408718ffeb2aeb0:
man: don't link to a page from itself (2023-05-14 00:57:26 …
```

[GIT PULL] man: don't link to a page from itself

---

man/io_uring_queue_init.3
man/io_uring_queue_init_mem.3
src/setup.c

The new preallocated ring support calculated the memory it needed in two
places, and the two calculations didn't match. Unify the two calculations to
prevent this.
The size calculation also didn't take `IORING_SETUP_CQE32` into account.
(This calculation should probably get unified across the various setup functions.)
In the `IORING_SETUP_CQE32` case, it was also possible to overrun a 2MB huge page;
detect and handle that case.
Use a normal-sized page if that suffices for the queue sizes, to save memory
and to work automatically on systems that don't have huge pages configured
(e.g. where `nr_hugepages` and `nr_overcommit_hugepages` still have their
default value of 0). For 4096-byte pages, this allows a queue size of 64 to fit
within two normal page allocations, and a queue size of 32 to …

[GIT PULL] Bugfixes for pre-allocated ring support

---

man/io_uring_setup.2
src/include/liburing/io_uring.h
src/setup.c
test/Makefile
test/reg-fd-only.c

This adds support for passing
`IORING_SETUP_REGISTERED_FD_ONLY | IORING_SETUP_NO_MMAP`
to any of the queue init functions.
----
```
The following changes since commit d39530a3f4b52ff2fab653eb3b2314e0aedc2d92:
Merge branch 'huge.2' (2023-06-09 11:29:05 -0600)
https://github.com/joshtriplett/liburing setup-registered-fd-only
for you to fetch changes up to 08e261a7f56a1d22f9e36c97ff33ea56c5e6f288:
Add test for IORING_SETUP_REGISTERED_FD_ONLY (2023-06-09 18:16:25 -0700)
Josh Triplett (5):
io_uring.h: Update to include IORING_SETUP_REGISTERED_FD_ONLY
man/io_uring_setup.2: Document IORING_SETUP_NO_MMAP
man/io_uring_setup.2: Document IORING_SETUP_REGISTERED_FD_ONLY
setup: Support …
```

[GIT PULL] Support IORING_SETUP_REGISTERED_FD_ONLY

---

src/Makefile

This fixes the build system to avoid undefined symbols that can appear due to compiler injecting calls to libc or compiler support functions (even though in principle we are disabling these in the build system). In particular this was an issue with the stack protection support.
----
```
The following changes since commit 76ce6f509e76df7547f051d59b8f883ea01c8cab:
Revert "setup: unify queue exit path" (2023-06-12 12:30:41 -0600)
https://github.com/guillemj/liburing pu/build-undef-syms
for you to fetch changes up to 9a127c05dd3b9fd0e4967c8d59d549706e89607f:
build: Fail the build if we have undefined symbols (2023-06-13 01:28:26 +0200)
Guillem Jover (2):
build: Disable stack protector …
```

[GIT PULL] Fix build system issues with undefined symbols

---

test/reg-fd-only.c

The reg-fd-only test fails on older kernels without IORING_SETUP_REGISTERED_FD_ONLY defined.
This change skips the test if io_uring_queue_init returns EINVAL.
----
```
The following changes since commit b3abdd798db6b6bfee6acac7ba1ee6698cc503ae:
Merge branch 'pu/build-undef-syms' of https://github.com/guillemj/liburing (2023-06-12 18:41:25 -0600)
https://github.com/spikeh/liburing fix_reg_fd_only_test
for you to fetch changes up to 75642b285a06a5715a62d0f7d62dd732ca0e9dfa:
test/reg-fd-only: skip on older kernels (2023-06-13 15:08:55 -0700)
David Wei (1):
test/reg-fd-only: skip on older kernels
test/reg-fd-only.c | 4 +++-
1 file changed, 3 insertions(+), 1 deletion(-)
```
----
<details> …

[GIT PULL] test/reg-fd-only: skip on older kernels

---

man/io_uring_setup.2

Plural should be used instead of singular.

Fix spelling in io_uring_setup.2

---

man/io_uring_enter.2
man/io_uring_register.2

EEXIST can arise in io_run_local_work, io_iopoll_check(), and io_cqring_wait(). In all cases, it seems due to the wrong thread being involved.
It looks like this can happen for io_uring_register() as well, so add it there, too.
1. I have followed the above pull request guidelines.
2. I have the rights to submit this work under the same license.
3. I agree to a Developer Certificate of Origin (see https://developercertificate.org for more information).
----
```
The following changes since commit 1e81a9a5943ba20dc68ef2b3269dc286d00f7c13:
test/coredump: make it explicit that the child is not returning (2023-06-15 14:10:18 -0600)
https://github.com/dankamongmen/liburing/ dankamongmen/enter-eexist
for you to fetch changes up to …
```

[GIT PULL] io_uring_enter2.2: add EEXIST to errors

---

configure
src/Makefile

Noticed 2 minor independent build failures
1.  Run `make --trace` without the configure step.
This causes make to build the target `config-host.mak` which
in turn invokes configure which generates an incorrect
`io_uring_version.h` file.
Fixed by setting `MAKEFLAGS=`
before generating `io_uring_version.h` file in the configure script
2. `/configure && make --shuffle=2836571325`
fails.
The build fails on parallel builds for me and the above command reproduces it.
Note that `--shuffle`options is available on make version >= 4.4
Target `ffi_libname` in `src/Makefile` should have an additional dependency
upon `$(liburing_sobjs)`
`make -n` also breaks but don't want to clutter this patch. If you give a go ahead, will fix that too.
----
```
The following changes since commit …
```

[GIT PULL] Minor Build Failure Fixes

---

test/Makefile

make -n i.e no-operation fails.
This is fixed by setting a conditional variable called LIBURING to ../src/liburing.a iff ../src/liburing.a exists in test/Makefile
----
```
The following changes since commit 33a326b64769c01dd5ff0e11e510641055c9354d:
Merge branch 'master' of https://github.com/stonebrakert6/liburing (2023-07-03 08:17:33 -0600)
https://github.com/stonebrakert6/liburing master
for you to fetch changes up to 1138f50b231538716795929c65d9e341532c70fc:
build: Fixed make -n (2023-07-05 12:01:32 +0530)
Kartik Mahajan (1):
build: Fixed make -n
test/Makefile | 6 ++++--
1 file changed, 4 insertions(+), 2 deletions(-)
```
----
<details> …

[GIT PULL] Minor Fix for make -n

---

CHANGELOG
man/io_uring_prep_cmd.3
src/include/liburing.h
src/include/liburing/io_uring.h
src/liburing-ffi.map
test/Makefile
test/socket-io-cmd.c

Add a new helper (io_uring_prep_cmd_sock) to call socket commands.
This includes the manpage (for the generic io_uring_prep_cmd) and a test case.
Signed-off-by: Breno Leitao <leitao@debian.org>
----
```
The following changes since commit ecfbf3ecd30a4b01b54848576f50b19363508f74:
register: use the right 'fd' depending on registration state (2023-07-24 20:20:23 -0600)
git@github.com:leitao/liburing.git ioctl_submitv2
for you to fetch changes up to 13b4a612ae5e4a8d67b0c9e55ddbfdf5b5df5b98:
test: socket io cmd operations (2023-07-27 06:44:15 -0700)
Breno Leitao (3):
uapi:  Sync with the kernel to get socket CMD
io_uring_prep_cmd: Create a new helper for command ops
test: socket io cmd …
```

Ioctl submitv3

---

man/io_uring_setup.2

The new io_uring_disabled sysctl can make io_uring_setup return -EPERM if it's set to disable io_uring, document this in the man pages.
Link: https://lore.kernel.org/all/x49y1i42j1z.fsf@segfault.boston.devel.redhat.com/
----
```
The following changes since commit 091e0931b3e54759b7e2ae66c2850a79768c8c23:
Remove old sendmsg lookup test case (2023-09-11 20:41:02 -0600)
https://github.com/matrizzo/liburing.git uring_sysctl
for you to fetch changes up to f26bc4261d9cea77aa826e6e1f2a2b8bf532c3b1:
man/io_uring_setup.2: add new reason for returning EPERM. (2023-09-13 08:11:53 +0000)
Matteo Rizzo (1):
man/io_uring_setup.2: add new reason for returning EPERM.
man/io_uring_setup.2 | 7 +++++++
1 …
```

[GIT PULL] Add new reason for returning EPERM from io_uring_setup

---

man/io_uring_submit.3

[GIT PULL] io_uring_submit: note specifics on return value for SQPOLL
Added the following behavior of io_uring_submit to the man page. When used with SQ_POLL and in the success case, the return value may not indicate the actual amount of successfully submitted submission queue entries, as mentioned in issue [88](https://github.com/axboe/liburing/issues/88)
Signed-off-by: Constantin Pestka constantin.pestka@web.de
----
```
The following changes since commit 7056087137dd6509cda8d617d7a6f536f44071f5:
man/io_uring_prep_timeout: add mention of version that added multishot (2023-10-04 16:28:25 -0600)
https://github.com/CPestka/liburing Update_Man_io_uring_submit
for you to fetch changes up to a65565e06670b98bfa04c719ce8f8b5ebfc4b278:
io_uring_submit: note …
```

[GIT PULL] io_uring_submit: note specifics on return value for SQPOLL

---

man/io_uring_queue_init.3

Add a note about kernel dropping CQEs when IORING_FEAT_NODROP is not present.
Signed-off-by: Alkis Evlogimenos <alkis@evlogimenos.com>
Fixes: https://github.com/axboe/liburing/issues/969
----
```
The following changes since commit 4b7a98ce3e766953eac1b18998d76d38dd9bff09:
Merge branch 'Update_Man_io_uring_submit' of https://github.com/CPestka/liburing (2023-10-12 10:47:51 -0600)
git@github.com:alkis/liburing man/io_uring_queue_init
for you to fetch changes up to 1a09c157a6b7954f099f5d27994c6a9d541fb85a:
man/io_uring_queue_init.3: Improve IORING_SQ_CQ_OVERFLOW docs (2023-10-18 07:31:17 +0000)
Alkis Evlogimenos (1):
man/io_uring_queue_init.3: Improve IORING_SQ_CQ_OVERFLOW docs …
```

[GIT PULL] man/io_uring_queue_init.3: Improve IORING_SQ_CQ_OVERFLOW docs

---

examples/io_uring-test.c

----
```
this pr is to fix #973 issue
```
----
<details>
1. To make everyone easily filter pull request from the email
notification, use `[GIT PULL]` as a prefix in your PR title.
```
[GIT PULL] Your Pull Request Title
```
2. Follow the commit message format rules below.
3. Follow the Linux kernel coding style (see: https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst).
1. The first line is title (don't be more than 72 chars if possible).
2. Then an empty line.
3. Then a description (may be omitted for truly trivial changes).
4. Then an empty line again (if it has a description).
5. Then a `Signed-off-by` tag with your real name and email. For example:
```
Signed-off-by: Foo Bar …
```

examples/io_uring-test: fix off-by-one in size checking

---

man/io_uring_setup.2

This section was referencing invalid member names and those members weren't present in the included struct definitions.
----
```
The following changes since commit caf7086a56bd118aff644cd3399aad3cfed03661:
Merge branch 'master' of https://github.com/piaoxuebingfeng/liburing (2023-10-26 12:44:15 -0600)
https://github.com/wlukowicz/liburing.git no_mmap_man
for you to fetch changes up to 60759ece628ea305d8717c81f8d1aeadb70b83c8:
man/io_uring_setup.2: tidy up IORING_SETUP_NO_MMAP docs (2023-10-28 17:27:40 +0100)
Wojciech Lukowicz (1):
man/io_uring_setup.2: tidy up IORING_SETUP_NO_MMAP docs
man/io_uring_setup.2 | 11 +++++++----
1 file changed, 7 insertions(+), 4 deletions(-)
```
---- …

[GIT PULL] man/io_uring_setup.2: tidy up IORING_SETUP_NO_MMAP docs

---

test/hardlink.c

This PR adds a test for the issue documented in #995. The new test will only run as root. Since the issue requires an upstream change, the test is not passing currently, but as a sanity check, the following patch can be applied to replace the call to uring's version of linkat with an equivalent call to regular linkat and the test will pass.
```diff
---
test/hardlink.c | 2 +-
diff --git a/test/hardlink.c b/test/hardlink.c
index cf170d0..2d328d1 100644
--- a/test/hardlink.c
+++ b/test/hardlink.c
@@ -95,7 +95,7 @@ int main(int argc, char *argv[])
if(geteuid()) {
fprintf(stdout, "not root, skipping AT_EMPTY_PATH test\n");
} else {
-		ret = do_linkat(&ring, fd, "", emptyname, AT_EMPTY_PATH);
+		ret = linkat(fd, "", AT_FDCWD, emptyname, …
```

[GIT PULL] test/hardlink: add test for `AT_EMPTY_PATH` flag

---

man/io_uring_enter.2

Fix a typo in the man page.
----
```
The following changes since commit 9d92636235f449c15892e01233d1b14149d59c1a:
test/reg-fd-only: test with huge pages as well (2023-11-24 16:25:10 -0700)
https://github.com/Hawk777/liburing.git typo
for you to fetch changes up to d8792f3c98ea0fe99783aa4ca9a3a62fec116111:
Fix typo in man page (2023-11-27 08:04:53 -0800)
Christopher Head (1):
Fix typo in man page
man/io_uring_enter.2 | 2 +-
```
----
<details>
1. To make everyone easily filter pull request from the email
notification, use `[GIT PULL]` as a prefix in your PR title.
```
[GIT PULL] …
```

[GIT PULL] Fix typo

---

configure
src/Makefile

GCC and clang have the -print-libgcc-file-name option to automatically print out the correct compiler runtime library to link to. This can be helpful in case the runtime library is named something other than libgcc (i.e. on a system where only LLVM's compiler-rt is used), or if libgcc is in a non-standard directory. If the option fails for whatever reason, fall back to using "-lgcc".
----
```
The following changes since commit 92b21aa1b4ea98e322c5eca9db1d94b837f4be75:
Rename ffi io_uring_prep_sock_cmd _> io_uring_prep_cmd_sock() (2023-12-11 13:14:54 -0700)
https://github.com/vimproved/liburing.git print-libgcc-file-name
for you to fetch changes up to 09b8ded9686f33f1044ad8c612f2281b865cd314:
Link against libgcc based on output of …
```

[GIT PULL] Link against libgcc based on output of -print-libgcc-file-name

---

man/io_uring_enter.2
man/io_uring_prep_futex_waitv.3
man/io_uring_queue_init.3
man/io_uring_setup.2

Several small man fixes:
- io_uring_queue_init(3): fix typo
- io_uring_enter(2): tidy up EBADR description
- io_uring_setup(2): tidy up IORING_SETUP_CLAMP description
- io_uring_prep_futex_waitv(3): fix signatures
----
```
The following changes since commit 7524a6adf4d6720a47bfa617b5cb2fd8d57f16d2:
t/no-mmap-inval: Replace `valloc()` with `t_posix_memalign()` (2023-12-19 08:22:16 -0700)
https://github.com/wlukowicz/liburing.git man-fixes
for you to fetch changes up to b1250d08dbe238830b49ea04ae6b4a12e69041ac:
man/io_uring_prep_futex_waitv.3: fix signatures (2024-01-02 18:24:48 +0000)
Wojciech Lukowicz (4):
man/io_uring_queue_init.3: fix typo
man/io_uring_enter.2: tidy up EBADR …
```

[GIT PULL] Several small man fixes

---

test/read-mshot.c

This patch adds a check for differing buffer sizes, and amkes sure that the returned size is correct.
This fails currently, but should work with https://lore.kernel.org/io-uring/20231105223008.125563-1-dyudaken@gmail.com/T/#t
----
```
The following changes since commit 78eef455c9538cbc145d7c658367f7662aeba39a:
liburing.spec: move to minor 6 (2023-11-04 15:15:11 -0600)
https://github.com/dylanZA/liburing fix1
for you to fetch changes up to 3df9b683d12e1c6bb68e48bfccaf9befddc86be9:
read-mshot.t: test with differing buffer size (2023-11-05 22:33:16 +0000)
Dylan Yudaken (1):
read-mshot.t: test with differing buffer size
test/read-mshot.c | 24 ++++++++++++++----------
1 file changed, 14 …
```

read-mshot.t: test with differing buffer size

---

man/io_uring_prep_timeout.3
man/io_uring_prep_timeout_update.3

Typo fix in `io_uring_prep_timeout`.
----
```
The following changes since commit b3addd05c912661b3a872382887a886d35ece536:
Add compatibility check for idtype_t (2024-01-31 12:46:19 -0700)
git@github.com:usurai/liburing.git man-typo
for you to fetch changes up to c5dfa645e7fa87202ed379aa5bc16a5646b20bf8:
man/io_uring_prep_timeout: Fix typo (2024-02-06 12:39:22 +0800)
usurai (1):
man/io_uring_prep_timeout: Fix typo
man/io_uring_prep_timeout.3        | 2 +-
man/io_uring_prep_timeout_update.3 | 2 +-
2 files changed, 2 insertions(+), 2 deletions(-)
```
----
<details>
1. To make everyone easily filter pull request from the email …

[GIT PULL] Fix typo in io_uring_prep_timeout

---

man/io_uring_prep_ftruncate.3
src/include/liburing.h
src/include/liburing/io_uring.h
src/liburing-ffi.map
test/Makefile
test/truncate.c

To accompany the patches I sent for adding ftruncate, here are the changes for usermode.
----
```
The following changes since commit 63342497bec87b72d4b415c8bed930c15ff83b0d:
test/read-mshot: check that IORING_CQE_F_MORE isn't set on error (2024-01-22 14:56:08 -0700)
git@github.com:tontinton/liburing.git truncate
for you to fetch changes up to c023393f3a3b960e3df77e5bcfd1b2e93e3b5e0f:
man/io_uring_prep_ftruncate: Add the new ftruncate command (2024-01-31 17:52:13 +0200)
Tony Solomonik (4):
Add ftruncate helpers
test/truncate: Add test for ftruncate
test/truncate: Add test for failure on truncate path
man/io_uring_prep_ftruncate: Add the new ftruncate command …
```

[GIT PULL] Add ftruncate

---

examples/proxy.c

Couple of minor proxy example fixes:
- if `IORING_FEAT_SEND_BUFS` is unavailable, the proxy still tries to use it by default,
- format fix for the verbose log when initially populating the recv buffer ring.
----
```
The following changes since commit af77bf2a82d2e71ffd1c353114ec24634c6e6d25:
examples/proxy: set 'len' for ring provided send buffers (2024-02-19 14:53:37 -0700)
https://github.com/wlukowicz/liburing.git proxy-fixes
for you to fetch changes up to e00c84cf052e73cdb88c0ced5bd2ee75d6f682f3:
examples/proxy: fix verbose log format (2024-02-20 22:20:15 +0000)
Wojciech Lukowicz (2):
examples/proxy: fix send ring default when unavailable
examples/proxy: fix verbose log format …
```

[GIT PULL] Minor proxy example fixes

---

Makefile
src/Makefile
test/Makefile

Introduce make uninstall in Makefile
Previously there was no uninstall feature, which was not user-friendly.
So now this commit adds the uninstall feature to the Makefile.
Following the installation funciton, we add two uninstallations target:
1-'uninstall': for src dir uninstallation
2-'uninstall-tests': for test dir uninstallation
In order to make sure that the path variables are valid, we also
include the 'config-host.mak' when performing the uninstall function.
Signed-off-by: Xinghui Li <korantli@tencent.com>

Introduce make uninstall in Makefile

---

src/include/liburing.h
src/queue.c
test/helpers.c

A few memory accesses don't seem correct to me, and a few seem slightly stricter than necessary.
Here are the rules in userspace, I think:
sq.ktail is read by the kernel
sq.khead is written by the kernel
cq.ktail is written by the kernel
cq.khead is read by the kernel
Locations that are written concurrently by the kernel must be loaded atomically; if they specify (to the user) that some memory is now available, they must be loaded with acquire semantics before the memory is read.
Similarly, locations that are read concurrently by the kernel must be written atomically; if they specify (to the kernel) that some memory is now available, they must be stored with release semantics after the memory is written to.
Note that without SQPOLL, sq is only accessed by the kernel in response to a …

[GIT PULL] Fix memory ordering/atomic access

---

src/include/liburing.h

flags were cleared out in io_uring_prep_rw, no documentation says one need to set sqe->flags after preping requests.
Ergo, add the IOSQE_BUFFER_SELECT flag back. To be fair, one should add ALL flags back if the call chain contains a
`io_uring_prep_rw`.
Fixes: https://github.com/axboe/liburing/issues/1126
Signed-off-by: gxu <georgexu420@gmail.com>
----
```
The following changes since commit f1dfb94bdaf1de14281030e28dd64f4d23d615a3:
examples/sendzc: test background polling (2024-04-08 21:45:58 -0600)
git@github.com:gxuu/liburing.git fix_clear_flags
for you to fetch changes up to e59d5039553ab9a325d5f2c10d6cc8f04d53bd97:
[fix] Initialize sqe earlier (2024-04-14 02:56:30 +0800)
gxu (2): …
```

[GIT PULL] re-add IOSQE_BUFFER_SELECT to flags

---

src/liburing-ffi.map

These symbols all appeared in the 2.6 version. One was added in 2.5, but the symbol name in the map file was wrong so it was not exported. The rest were all added in 2.6 but in the wrong nodes, either 2.4 or 2.5.
We cannot fix these now because the version is now attached to the symbols, so the best we can do w/o breaking ABI is to document this in the map file so that other people do not get confused.
Signed-off-by: Guillem Jover <guillem@hadrons.org>
----
```
The following changes since commit eb267a661a1636e69969d210654d90513fe81c2f:
man: fix IORING_REGISTER_RING_FDS docs (2024-05-03 16:17:41 -0600)
https://github.com/guillemj/liburing pu/libffi-symbols
for you to fetch changes up to 222b46ddc07109ba9232fb0140bbdec38b742607:
liburing-ffi.map: Add …
```

[GIT PULL] liburing-ffi.map: Add comments for symbols added in wrong version node

---

test/coredump.c

The test case tries to segfault so that it can generate a coredump. So this is an expected artifact from the test case, that we should be cleaning up, and not something that requires investigation by the builder.
----
```
The following changes since commit eb267a661a1636e69969d210654d90513fe81c2f:
man: fix IORING_REGISTER_RING_FDS docs (2024-05-03 16:17:41 -0600)
https://github.com/guillemj/liburing pu/test-clean
for you to fetch changes up to 20e99f6a6cb5916fcc96c05dc71804a811deeddf:
test: Remove the coredump if coredump.t managed to generate one (2024-05-05 17:13:01 +0200)
Guillem Jover (1):
test: Remove the coredump if coredump.t managed to generate one
test/coredump.c | 1 +
1 file …
```

[GIT PULL] test: Remove the coredump if coredump.t managed to generate one

---

test/socket-getsetsock-cmd.c

Make the socket-getsetsock-cmd run
----
```
he following changes since commit 2d80864dfb83c158b2f1b273ee3d9be21b1729e5:
test/msg-ring: use local ring for remote waiter (2024-05-29 11:07:22 -0600)
https://github.com/axboe/liburing.git master
for you to fetch changes up to 013f87d498a8038890e55dda7665f0c3707205d5:
test/socket-getsetsock-cmd: remove fprintfs (2024-05-30 06:26:17 -0700)
Breno Leitao (1):
test/socket-getsetsock-cmd: remove fprintfs
test/socket-getsetsock-cmd.c | 4 ----
1 file changed, 4 deletions(-)
```
----
1. I have followed the above pull request guidelines.
2. I have the rights to submit this work under the same license.
3. I agree to a Developer Certificate of Origin …

[GIT PULL] test/socket-getsetsock-cmd: remove fprintfs

---

man/io_uring_enter.2

Correct IORING_OP_EPOLL_CTL documentation for 'off' and 'addr' parameters and fix typo.
----
```
The following changes since commit b68cf47a120d6b117a81ed9f7617aad13314258c:
man/io_uring_enter: correct struct type referenced for timeouts (2024-06-03 13:01:56 -0600)
https://github.com/Andreas-Bur/liburing
for you to fetch changes up to 98a52fe8d350ac92834896d8be0853690159c46f:
man/io_uring_enter: fix IORING_OP_EPOLL_CTL documentation (2024-06-16 21:02:27 +0200)
Andreas Bur (1):
man/io_uring_enter: fix IORING_OP_EPOLL_CTL documentation
man/io_uring_enter.2 | 6 +++---
1 file changed, 3 insertions(+), 3 deletions(-)
```
----
<details> …

[GIT PULL] man/io_uring_enter: fix IORING_OP_EPOLL_CTL documentation

---

test/buf-ring-nommap.c

The test crashes when run under the openSUSE build system. It sets `MALLOC_PERTURB_=69` in the environment, so the allocated memory is initialized to `0xba`.
Later in `io_uring_get_sqe()` -> `_io_uring_get_sqe()`:
```
1424           if (next - head <= sq->ring_entries) {
(gdb) p *sq
$2 = {khead = 0x55555555d000, ktail = 0x55555555d004,
kring_mask = 0x55555555d010, kring_entries = 0x55555555d018,
kflags = 0x55555555d024, kdropped = 0x55555555d020, array = 0x0,
sqes = 0x55555555c000, sqe_head = 0, sqe_tail = 0, ring_sz = 0,
ring_ptr = 0x55555555d000, ring_mask = 0, ring_entries = 1, pad = {0, 0}}
(gdb) p sq->ring_entries
$3 = 1
(gdb) p next
$4 = 1
(gdb) p/x head
$6 = 0xbabababa
```
And that causes a crash, of course.
Fix that by zeroing the memory after `posix_memalign()`.

test/buf-ring-nommap: zero the ringbuf memory

---

liburing.pc.in

Add `-D_GNU_SOURCE` to Cflags to avoid the following musl build failure with applications using liburing (e.g. libdex) raised since version 2.6 and c427ed678f39fd144d784f2e970bd8c52f425e14 which reverted c34070e08199491fe9653617364f4aea9b9b22be:
```
In file included from ../src/dex-uring-aio-backend.c:29: /home/autobuild/autobuild/instance-7/output-1/host/mips-buildroot-linux-musl/sysroot/usr/include/liburing.h:224:39: error: unknown type name 'cpu_set_t'
224 |                                 const cpu_set_t *mask);
|                                       ^~~~~~~~~
/home/autobuild/autobuild/instance-7/output-1/host/mips-buildroot-linux-musl/sysroot/usr/include/liburing.h:1212:48: error: unknown type name 'loff_t'; did you mean 'off_t'?
1212 |                                        int fd, …
```

[GIT PULL] liburing.pc.in: add -D_GNU_SOuRCE to Cflags

---

src/include/liburing/io_uring.h

`io_uring_cqe`'s `user_data` field refers to `sqe->data`, but `io_uring_sqe` does not have a `data` field. Fix the comment to say `sqe->user_data`.
----
```
The following changes since commit 401b3e4bde2316d35e93b548269c72bbb64adc02:
man/io_uring_prep_timeout.3: correct IORING_TIMEOUT_ETIME_SUCCESS (2024-08-13 06:44:12 -0600)
git@github.com:calebsander/liburing.git fix/user_data
for you to fetch changes up to a528be6ff0478b40b384dcd29c4836668e8e62ec:
io_uring.h: fix user_data field name in comment (2024-08-15 21:09:56 -0600)
Caleb Sander Mateos (1):
io_uring.h: fix user_data field name in comment
src/include/liburing/io_uring.h | 2 +-
```

io_uring.h: fix user_data field name in comment

---

.github/actions/codespell/stopwords
.github/workflows/codespell.yml
debian/control
examples/proxy.c
man/io_uring_buf_ring_available.3
man/io_uring_prep_recv.3
man/io_uring_prep_send.3
man/io_uring_prep_symlinkat.3
man/io_uring_register_eventfd.3
man/io_uring_submit.3
src/include/liburing/io_uring.h
test/ignore-single-mmap.c

This series include a couple of commits for typo fixes, and another one introducing a new GitHub workflow to run codespell over the source tree, to catch regressions.
The typo fixes modify the header which is usually imported from Linux, but otherwise we'd need to mark that typo as a stopword. The workflow uses a more recent Ubuntu release than the other workflows, otherwise the older codespell  generates more false positives.
----
```
The following changes since commit 27758779626a28d416a58a824f85fb118a63a4d5:
test/recvsend_bundle: don't fail on short receives (2024-08-26 19:26:15 -0600)
https://github.com/guillemj/liburing.git pu/typos
for you to fetch changes up to bb1d03aeb6c7bb64770f70dd453e9c241d96450f:
.github: Add new codespell CI test …
```

[GIT PULL] Typo fixes and CI addition

---

man/io_uring_enter.2

This makes three small changes to the man pages of io_uring_enter:
1. Adds documentation for the possible return value EEOWNERDEAD (i.e. ring uses sqpoll and some one killed the sqpoll kthread)
2. Adds a more specific description to when a thread is "invalid" and thus causes a return value of EEXIST. Which as far as i could tell boils down to IORING_ENTER_GETEVENTS && IORING_SETUP_DEFER_TASKRUN && current != ctx->submitter_task
3. Fixes a small grammatical error 
----
```
The following changes since commit cc74667886e92a0a1b3a279ed5f2f527c5d9f3e0:
Update CHANGELOG (2024-08-31 06:20:06 -0600)
https://github.com/CPestka/liburing man_io_uring_enter
for you to fetch changes up to 6981007646a70326071ca3fa6d0b518ce0213ca4:
man/io_uring_enter: Add missing …
```

[GIT PULL] man/io_uring_enter: add missing and clarify another return value

---

man/io_uring_free_buf_ring.3

Trivial documentation fix: The function returns zero or `-errno`, not a pointer. Also, this removes the "buffe ring" typo, which I am probably the only person to find funny.
----
```
The following changes since commit b0cf23de76df798833f271579b31bdd70cb50863:
test: return skipped if we don't have permission to open file (2024-09-03 10:52:32 -0600)
git@github.com:nigoroll/liburing.git buffe_ring
for you to fetch changes up to 9448db157751a3a5b8618ff6c0fb81fc73443e8e:
man/io_uring_free_buf_ring.3: Fix return value documentation (2024-09-03 19:13:04 +0200)
Nils Goroll (1):
man/io_uring_free_buf_ring.3: Fix return value documentation
man/io_uring_free_buf_ring.3 | 2 +-
1 file changed, 1 …
```

[GIT PULL] Fix io_uring_free_buf_ring return value documentation

---

configure

If ublk_cmd.h does not contain modern command definitions such as UBLK_U_CMD_START_DEV the ublk io_uring commands cannot be used. These definitions have only been added last year, so there will be users who will not have these available.
Tested on my raspberry pi 4 with debian/bookworm and kernel 6.1.0-rpi7-rpi-v8
----
```
<The following changes since commit f2dc904171f36f32a6f2566d1e6b12398ec3bb4f:
man/io_uring_prep_close: note on direct descriptor failure cases (2024-09-05 09:00:54 -0600)
git@github.com:Oipo/liburing.git 
for you to fetch changes up to 60ae198ac7dcdfc0580a354b203df092db81111c:
configure: don't enable ublk if modern commands not available (2024-09-06 22:45:08 +0200) …
```

configure: don't enable ublk if modern commands not available

---

man/io_uring_enter.2

This adds documentation for the following missing Op codes:
1. IORING_OP_GETXATTR
2. IORING_OP_SETXATTR
3. IORING_OP_FGETXATTR
4. IORING_OP_FSETXATTR
5. IORING_OP_BIND
6. IORING_OP_LISTEN
7. IORING_OP_FTRUNCATE
8. IORING_OP_SENDMSG_ZC
9. IORING_OP_READ_MULTISHOT
10. IORING_OP_FUTEX_WAIT
11. IORING_OP_FUTEX_WAITV
12. IORING_OP_FUTEX_WAKE
It also adds documentation about:
1. the undocumented ability to sync file ranges rather than the whole file with IORING_OP_FSYNC see #990
2. the "level" and "edge triggered" behavior of IORING_OP_POLL_ADD see #1014
3. how to enforce ordering between requests after the remark in IORING_OP_FSYNC how one can not rely on ordering per default
As it seems there are no man pages for the new futex syscalls yet (they are normally done by glibc right?) I'm not very …

[GIT PULL] man/io_uring_enter: Add missing Op codes and some minor other additions

---

man/io_uring_enter.2

This 
1. Adds documentation for
1. IORING_TIMEOUT_MULTISHOT
2. IORING_TIMEOUT_ETIME_SUCCESS
3. some possible errors regarding the timeout op
2. Updates the sqe definition in the man page to the current one in io_uring.h
3. Attempts to fix various formatting errors/inconsistencies, like use of .I rather than .B for flags described in man page.
4. Add some small remarks about the return value of the install registered fd op and the default clock of the timeout op
----
```
The following changes since commit ad42755a00e27eaeb20089c2984b0211d3292a96:
test/futex: don't leave futex wait pending (2024-09-14 10:04:40 -0600)
https://github.com/CPestka/liburing io_uring_enter_man
for you to fetch changes up to 1438d97086c349859709b51d1a12ad120a40b1f8: …
```

[GIT PULL] man/io_uring_enter: Add doc for timeout flags (multishot, etime_success), update sqe definition, various fmt-ing fixes

---

test/Makefile

building nolibc.c fails for non nolibc targets
Fixes
In file included from nolibc.c:33:
./../src/lib.h:20:2: error: "This arch doesn't support building liburing without libc"
20 | #error "This arch doesn't support building liburing without libc"
|  ^
1 error generated.

test: Compile nolibc.c only when CONFIG_NOLIBC is set

---

test/linked-defer-close.c

This makes the linked-defer-close test work correctly without relying on
improper usage of IOSQE_IO_LINK.
The test will now issue three sends with
IOSQE_CQE_SKIP_SUCCESS | IOSQE_IO_LINK followed by a close with
IOSQE_CQE_SKIP_SUCCESS on a ring setup with IORING_SETUP_DEFER_TASKRUN.
On an incorrectly behaving kernel the connection will not be closed and
remain open.
This test first fails on kernel commit 846072f16eed3b3fb4e59b677f3ed8afb8509b89
Signed-off-by: Jan Hendrik Farr <kernel@jfarr.cc>

test/linked-defer-close: make test work without improper IOSQE_IO_LINK

---

man/io_uring.7

This:
1. Fixes a couple of fmt things
2. Updates the sqe struct
3. Moves the read op as an example of an sqe to the bullet point where sqes are described first
4. Adds a remark that the generally described order of operation in the beginning of the man page can significantly change based on config parameters and usage
5. Adds a pointer to where one can find info about memory models after the statement that, while they are important here, they are out of scope for the man page
----
```
The following changes since commit 206650ff72b6ea4d76921f9c91ebfffd9902e6a0:
test/fixed-hugepage: skip test on -ENOMEM (2024-09-27 10:27:10 -0600)
https://github.com/CPestka/liburing io_uring_man
for you to fetch changes up to 8a7810d0ac44fcb3082ece0f9d699414d8d590b3: …
```

[GIT PULL] man/io_uring: Small fixes and additions

---

src/include/liburing.h

I thought it was a bit odd that the macro repedatly does the atomic load. While when using it one can amortize the atomic store following the loop, I don't really see why one wouldn't want to do the same for the load, like is already being done in io_uring_peek_batch_cqe(). Maybe I'm missing smth.
This pulls the load out of the loop into a local. Not sure if this is acceptable. I gave it a long ugly name to avoid name collisions, but still. Maybe making a new macro would be better.
----
```
The following changes since commit 206650ff72b6ea4d76921f9c91ebfffd9902e6a0:
test/fixed-hugepage: skip test on -ENOMEM (2024-09-27 10:27:10 -0600)
https://github.com/CPestka/liburing for_each_cqe
for you to fetch changes up to …
```

[GIT PULL] liburing/io_uring_for_each_cqe: Pull load acquire out of for loop

---

.gitignore
examples/Makefile
examples/kdigest.c

When built with CONFIG_CRYPTO_USER_API_HASH enabled, Linux exposes a
socket based API for hashing data. When coupled with uring
IOSQE_IO_LINK, file hashing can be done in quite an efficient manner,
as demonstrated in this link-cp.c based example.
Signed-off-by: David Disseldorp <ddiss@suse.de>

examples/kdigest: add AF_ALG hash example

---

man/io_uring_prep_openat.3
man/io_uring_prep_openat2.3

* minor rearrangement & split of pargraph
* clarify that IOSQE_FIXED_FILE is for subsequent sqe, not this one
* note that dfd is always a regular file descriptor
----
```
The following changes since commit 352c8ab127e1924d64fbbd2bf337c06d1c1abd03:
examples/kdigest: misc updates and improvements (2024-10-01 16:44:35 -0600)
https://github.com/aconz2/liburing man-open2
for you to fetch changes up to d7c02c9a396cfba5cfa9ffe9b113cb7428096766:
man/prep_openat{2}: clarify IOSQE_FIXED_FILE (2024-10-02 11:59:29 -0500)
Andrew Consroe (1):
man/prep_openat{2}: clarify IOSQE_FIXED_FILE
man/io_uring_prep_openat.3  | 41 +++++++++++++++++++++++------------------
man/io_uring_prep_openat2.3 | 46 …
```

[GIT PULL] man/prep_openat{2}: clarify IOSQE_FIXED_FILE

---

examples/kdigest.c
test/bind-listen.c

A couple of minor follow-ups for the kdigest example and one test/bind-listen buflen fix.
----
```
The following changes since commit 352c8ab127e1924d64fbbd2bf337c06d1c1abd03:
examples/kdigest: misc updates and improvements (2024-10-01 16:44:35 -0600)
https://github.com/ddiss/liburing.git kdigest_follow_ups
for you to fetch changes up to 33de51d36c3e78dfea2a93abf27dc4f2809f43b6:
examples/kdigest: print whether bundled sends were used (2024-10-03 03:00:09 +0000)
David Disseldorp (3):
test/bind-listen: fix incorrect io_uring_prep_recv buflen
examples/kdigest: reuse I/O buffer for hash result
examples/kdigest: print whether bundled sends were used
examples/kdigest.c | 15 ++++++++------- …
```

[GIT PULL] minor kdigest follow-ups

---

man/io_uring_register.2

When using `IORING_REGISTER_RING_FDS`, the `data` field of the structure should *contain*, not *point to*, the file descriptor to register.
----
```
The following changes since commit 80272cbeb42bcd0b39a75685a50b0009b77cd380:
Rename '*ret' to '*err' for io_uring_setup_buf_ring() (2024-10-23 11:13:23 -0600)
https://github.com/Hawk777/liburing.git register-ring-fds-not-pointer
for you to fetch changes up to 1bd53c8ad3cac4d73ede7801f52ea3b4d09fa88d:
Fix description of data for REGISTER_RING_FDS (2024-10-26 18:20:14 -0700)
Christopher Head (1):
Fix description of data for REGISTER_RING_FDS
man/io_uring_register.2 | 2 +-
```
----
<details> …

[GIT PULL] Fix description of data for REGISTER_RING_FDS

---

man/io_uring_peek_cqe.3

Due to an unclosed quotation mark, the io_uring_peek_batch_cqe prototype was rendered like this:
int io_uring_peek_batch_cqe(struct io_uring *ring,
struct io_uring_cqe **cqe_ptrs,
unsigned count );"
----
```
The following changes since commit a0d60e796006fa3dc1a75250a2039abffa52da19:
man/io_uring_prep_openat2: get rid of non-existent flags argument (2024-11-20 07:52:59 -0700)
https://github.com/tavianator/liburing fix-quotmark
for you to fetch changes up to a35136ae9d75d726f84f387447253cf25dac646c:
man/io_uring_peek_cqe: fix unclosed quotation mark (2024-11-20 12:12:01 -0500)
Tavian Barnes (1):
man/io_uring_peek_cqe: fix unclosed quotation mark
man/io_uring_peek_cqe.3 | 2 +-
1 file …
```

man/io_uring_peek_cqe: fix unclosed quotation mark

---

man/io_uring.7
man/io_uring_prep_msg_ring_fd.3
man/io_uring_prep_read_fixed.3
man/io_uring_prep_timeout.3
man/io_uring_prep_timeout_update.3
man/io_uring_prep_write_fixed.3
man/io_uring_register.2
man/io_uring_register_buf_ring.3
man/io_uring_setup_buf_ring.3
man/io_uring_sq_space_left.3

Several fixes and improvements to the man pages:
- fixed buf ring registration flags,
- fixed title headings,
- improved IORING_REGISTER_BUFFERS2 description.
----
```
The following changes since commit 9032c80cdc7e64bf146ec801fa8917bed6493075:
man/io_uring_register_sync_cancel.3: update io_uring_sync_cancel_reg (2024-11-29 09:14:14 -0700)
https://github.com/wlukowicz/liburing man-fixes
for you to fetch changes up to 416d96ce5a4bb0ffb366b93a3c7333842cc290d8:
man/io_uring_register.2: improve IORING_REGISTER_BUFFERS2 description (2024-12-01 15:44:56 +0000)
Wojciech Łukowicz (3):
man: fix buf ring registration flags
man: fix title headings
man/io_uring_register.2: improve …
```

[GIT PULL] Man improvements

---

test/init-mem.c

This is a similar fix to commit 8100d7b5f862 (test/buf-ring-nommap: zero the ringbuf memory). The same is needed for test/init-mem as it crashes with `MALLOC_PERTURB_=69` too.
So zero the ringbuf memory after posix_memalign() too.
Fixes #1291.

test/init-mem: zero the ringbuf memory

---

test/fallocate.c

In kernel 6.4, the result still can be `EOPNOTSUPP`. Check for that too.

test/fallocate: check for `EOPNOTSUPP` too (6.4)

---

man/io_uring_sqe_set_buf_group.3
src/include/liburing.h
src/liburing-ffi.map
test/recv-multishot.c

Adds the free function io_uring_sqe_set_buf_group so that users of liburing-ffi don't have to navigate the complex io_uring_sqe structure.
----
```
The following changes since commit c3d5d6270cd5ed48d817fc1e8e95f7c8b222f2ff:
man/io_uring_prep_cancel.3: correct io_uring_prep_cancel_fd() flags (2024-12-07 13:35:56 -0700)
https://github.com/cmazakas/liburing.git set-buf-group
for you to fetch changes up to 1dd8059a7d66d9126021154c24945623ef62a834:
add io_uring_sqe_set_buf group (2024-12-09 12:00:26 -0800)
Christian Mazakas (1):
add io_uring_sqe_set_buf group
man/io_uring_sqe_set_buf_group.3 | 32 ++++++++++++++++++++++++++++++++
src/include/liburing.h           |  6 ++++++ …
```

[GIT PULL] add io_uring_sqe_set_buf group

---

test/timeout.c

This test catches a bug in the kernel where when a multishot timeout operation is updated with a new value, only the first timeout is updated and the subsequent timeouts are not.
----
```
The following changes since commit 1a780b1fa6009fe9eb14dc48a99f6917556a8f3b:
test/read-inc-file: skip if argument is given (2025-01-03 10:08:06 -0700)
https://github.com/cmazakas/liburing.git multishot-timeout-update
for you to fetch changes up to 15283749ebf9707e65bc82a81052e499ed1ba2d7:
test/timeout: update multishot timeout operations (2025-01-06 08:01:03 -0800)
Christian Mazakas (1):
test/timeout: update multishot timeout operations
test/timeout.c | 150 …
```

[GIT PULL] test/timeout: update multishot timeout operations

---

man/io_uring_prep_recv.3

Specifically, explain how to identify multiple buffer ids upon bundle completion.
----
```
The following changes since commit a5dd7f85d4b667aeb687afc562ff9750044b42c2:
man/io_uring_clone_buffers: mention that both rings must share mm (2025-01-14 11:06:56 -0700)
https://github.com/romange/liburing Pr1
for you to fetch changes up to 73bb0ac90437f87b8ecbde50fe30fa25a4df1ae5:
man/io_uring_prep_recv: expand on how to handle bundles (2025-02-03 14:37:41 +0200)
Roman Gershman (1):
man/io_uring_prep_recv: expand on how to handle bundles
man/io_uring_prep_recv.3 | 14 ++++++++++----
1 file changed, 10 insertions(+), 4 deletions(-)
```
----
<details> …

man/io_uring_prep_recv: expand on how to handle bundles

---

examples/proxy.c

When proxy works without multishot, it needs to submit additional receive. Old code uses direction in index 0 without considering BIDI and it triggers assertion for checking cd->pending_recv. This patch fixes to use corresponding direction also fd.
Issue: #1338
----
```
The following changes since commit 6c509e2b0c881a13b83b259a221bf15fc9b3f681:
test/sqwait: cleanup allocated iovecs (2025-01-22 19:48:36 -0700)
https://github.com/SidongYAng/liburing fix-proxy-bidi
for you to fetch changes up to 7f0089994c53d42478445c5b17d2223103eec275:
examples/proxy: Fix for BIDI (2025-02-17 17:05:41 +0000)
Sidong Yang (1):
examples/proxy: Fix for BIDI
examples/proxy.c | 2 +-
1 file changed, 1 …
```

[GIT PULL] examples/proxy: Fix for BIDI

---

.github/workflows/build.yml

The GitHub Actions workflow file erroneously tests a branch on a non-existent field of the build matrix. Fixing the typo means that the correct workflows are now run.
----
```
The following changes since commit 08468cc3830185c75f9e7edefd88aa01e5c2f8ab:
Merge branch 'Pr1' of https://github.com/romange/liburing (2025-02-03 05:42:36 -0700)
https://github.com/cmazakas/liburing.git gha-fix
for you to fetch changes up to b16733b1b2302cab50098d402688ac3451902d8c:
workflows/build.yml: fix sanitizer typo (2025-02-07 07:22:12 -0800)
Christian Mazakas (1):
workflows/build.yml: fix sanitizer typo
.github/workflows/build.yml | 4 ++--
1 file changed, 2 insertions(+), 2 deletions(-)
```
----
1. I …

[GIT PULL] workflows/build.yml: fix sanitizer typo

---

.github/workflows/build.yml

Tooling like bindgen seems to encounter difficulties when using clang that isn't installed via apt. Using the default packaged clang from the Ubuntu apt repos simplifies the workflow and provides the build environment with a relatively modern version of clang (clang-18).
clang-18 should be more than sufficient to test building the library.
----
```
The following changes since commit 08468cc3830185c75f9e7edefd88aa01e5c2f8ab:
Merge branch 'Pr1' of https://github.com/romange/liburing (2025-02-03 05:42:36 -0700)
https://github.com/cmazakas/liburing.git gha-clang
for you to fetch changes up to 019c04dad97e5d3b78eec9786e89e17b021d7fd0:
workflows/build.yml: install default ubuntu-24.04 clang (2025-02-07 07:26:32 -0800) …
```

[GIT PULL] workflows/build.yml: install default ubuntu-24.04 clang

---

test/connect.c
test/iopoll-overflow.c
test/resize-rings.c
test/timeout.c
test/wq-aff.c

Fix some testing gaps where errors would not cause the tests to fail.
Also add some `-EINVAL` result checks to allow tests to skip rather than fail on older kernels (tested on 5.15).
----
```
The following changes since commit 5c788d514b9ed6d1a3624150de8aa6db403c1c65:
Fix missing `aligned_alloc()` on some Android devices (2025-02-20 07:51:15 -0700)
git@github.com:calebsander/liburing.git fix/test-einval
for you to fetch changes up to c7fd16a7d7af305384c44baa74b4bd07bb378295:
test/wq-aff: check io_uring_queue_init_params() success (2025-02-23 11:22:53 -0700)
Caleb Sander Mateos (6):
test/connect: propagate return value from test()
test/connect: skip on -EINVAL in io_uring_setup …
```

[GIT PULL] Test fixes and compatibility with older kernels

---

man/io_uring_peek_cqe.3
src/include/liburing.h
src/queue.c
src/sanitize.c
src/setup.c

Consolidate duplicated code and other cleanups in io_uring_get_sqe() and CQE polling.
Introduce a `struct io_uring_cqe_iter` and related functions to provide a non-macro alternative to `io_uring_for_each_cqe()`.
Also fix some inaccuracies in the man page for `io_uring_peek_batch_cqe()`.
----
```
The following changes since commit fe8ebe7995512696d94e704c2823e30faa0bdcff:
Merge branch 'fix/test-einval' of https://github.com/calebsander/liburing (2025-02-24 07:09:48 -0700)
git@github.com:calebsander/liburing.git refactor/big
for you to fetch changes up to e2386cc990744d8be0f60a66b6cf1cafd9d919c7:
Add io_uring_cqe_shift_from_flags() helper (2025-02-24 23:03:16 -0700)
Caleb Sander Mateos …
```

[GIT PULL] SQ and CQ code cleanup

---

man/io_uring.7

Add notes about parallel send/receive to the manual.
The overlapping of operations on stream-oriented files can cause subtle 
reordering behaviors that have confused multiple people over time. 
Add a new paragraph that clearly outlines that overlapping sends,
or overlapping receives, is generally unsafe.
Context: https://github.com/axboe/liburing/discussions/1372
Related issues with previous discussions:
- https://github.com/axboe/liburing/issues/1359
- https://github.com/axboe/liburing/issues/1282
- https://github.com/axboe/liburing/issues/1001
Signed-off-by: Francis Brosseau <francis@malagauche.com>

[GIT PULL] Add notes about parallel send/receive to the manual.

---

man/io_uring.7

There is no IOURING_ENTER_GETEVENTS, should be IORING_ENTER_GETEVENTS without U.
----
```
The following changes since commit cc7a17ecce8b6d692c4d1492d4877161166bc322:
io_uring.h: Use Tab to separate macro define value (2025-05-07 12:19:58 -0600)
https://github.com/Sberm/liburing.git master
for you to fetch changes up to 4d26b4b6ac326aa0d28b1b2ce4c3724bd5105df9:
man/io_uring.7: Fix a typo in the comment of the example (2025-05-07 15:01:57 -0700)
Howard Chu (1):
man/io_uring.7: Fix a typo in the comment of the example
man/io_uring.7 | 2 +-
```
----
<details>
1. To make everyone …

man/io_uring.7: Fix a typo in the comment of the example

---

man/io_uring_enter.2
src/arch/generic/syscall.h
src/arch/syscall-defs.h
src/include/liburing.h
src/syscall.c
test/wait-timeout.c

Since kernel 5.11, `io_uring_enter2()` accepts a `IORING_ENTER_EXT_ARG` flag allowing a `struct io_uring_getevents_arg * `to be passed in place of the `sigset_t *` argument. Kernel 6.12 adds the `IORING_ENTER_EXT_ARG_REG` flag, which interprets the argument as an offset into a region of `struct io_uring_reg_wait`'s registered with `IORING_REGISTER_CQWAIT_REG`.
Kernel 5.11 was released over 4 years ago, so it seems more accurate for the argument type to be a `void *` rather than a `sigset_t *`. Change the argument type and rename it from "sig" to "arg" to match the man page. Using `void *` removes the need for a confusing pointer cast for callers passing `struct io_uring_getevents_arg *`.
----
```
The following changes since commit 47eacd321f107eb53b1d872d5a376ba7885e8e76:
Merge branch …
```

[GIT PULL] syscall: update io_uring_enter2() signature

---

src/sanitize.c

Currently the test suite will segfault when running the test epwait.t because of an out-of-bounds access of sanitizer handlers. We add the missing ops and keep the table in sync with the list in io_uring.h
----
```
The following changes since commit 4ee26f88a0592675bf623b76e116124956a048ba:
Merge branch 'fix/io_uring_enter2-signature' of https://github.com/calebsander/liburing (2025-05-14 13:33:24 -0600)
https://github.com/cmazakas/liburing sanitizer-fix
for you to fetch changes up to a1040018719aba096b1f985b09864d9edb58c603:
src/sanitize: add missing op entries (2025-05-18 10:24:13 -0700)
Christian Mazakas (1):
src/sanitize: add missing op entries
src/sanitize.c | 4 ++++
1 file …
```

[GIT PULL] src/sanitize: add missing op entries

---

configure

In modern package management system, such as conan/vcpkg, compat.h was generated on the building machine, and then used on other machines. It can cause compiling errors: __kernel_timespec redefined.
If __has_include defined, generated preprocessor check in campat.h otherwise, fallback to current solution.
----
```
The following changes since commit fe1fc8c0516954d345ee5f7613b8e4740b69b9c1:
liburing.h: Only use `IOURINGINLINE` macro for FFI functions (2025-06-30 15:39:05 -0600)
https://github.com/kexianda/liburing.git fix
for you to fetch changes up to 06667b2a1a945527e73b6f7fbe2f9fdc6071b519:
configure: fix compile error of __kernel_timespec (2025-07-02 16:53:40 +0800)
Xianda Ke (1): …
```

[GIT PULL] configure: fix compile error of __kernel_timespec

---

src/include/liburing.h

__io_uring_peek_cqe() is on the critical path for the user to consume completion-queue entries. It load_acquires the tail, loads the head, uses the head to index into the cq ring.
The C memory consistency model does not enforce ordering for address dependencies, like the one seen in:
```
LD1: unsigned head = *ring->cq.khead;
...
LD2: cqe = &ring->cq.cqes[(head & mask) << shift];
```
where LD2 is address-dependent on LD1. This means that LD2 could load a stale cqe due to LD1 being ordered after LD2. If instead, LD1 was a smp_load_acquire, the ordering would be enforced and correct cqes would be loaded.
Signed-off by: Soham Bagchi <soham.bagchi@utah.edu>
Co-authored by: Marco Elver <elver@google.com>
Co-authored by: Vijay Nagarajan <vijay@cs.utah.edu>
Co-authored by: Ryan Stutsman …

[GIT PULL] smp_load_acquire(ring->cq.khead) in __io_uring_peek_cqe() for consistent dereferencing

---

test/wq-aff.c

I came across a pipeline which is using tests but against the VM with single CPU, so inevitably wq-aff failed there.
While trivial and perhaps obvious it might be better to T_EXIT_SKIP wq-aff in such cases.

test: Add CPUs count check in wq-aff

---

man/io_uring_wait_cqe_timeout.3
man/io_uring_wait_cqes.3

This was something I wanted to look up in the man page, and found lacking. It was little hassle to dive into the code and check there, but for completeness sake, I think this is a useful change.
----
```
The following changes since commit 5ffa0ff1d98ec8031a1888a043a2b939b29436fe:
man/send*: updates for supported send flags (2025-07-30 06:47:29 -0600)
git@github.com:mbr0wn/liburing.git mbr0wn/man-add-ETIME
for you to fetch changes up to 8e2b89fb3e1886f652ecac00a71e7879cbafa0d3:
man/wait_cqe*: Describe -ETIME return value (2025-07-31 16:16:57 +0200)
Martin Braun (1):
man/wait_cqe*: Describe -ETIME return value
man/io_uring_wait_cqe_timeout.3 | 3 ++-
man/io_uring_wait_cqes.3        | 2 ++ …
```

[GIT PULL] man/wait_cqe*: Describe -ETIME return value

---

src/include/liburing.h

io_uring_prep_bind can be updated to accept its address by const pointer which makes it consistent with the documented bind system call. We also replace a raw `static inline` with the proper macro for the recently introduced io_uring_skip_cqe helper. And finally, we introduce a missing noexcept specifier for io_uring_cqe_get_data.
----
```
The following changes since commit e951bf0c08c81a2ea0c4b7bca7e4494f2043d367:
man: include common -ENOMEM error for zero copy send (2025-09-22 09:55:44 -0600)
git@github.com:cmazakas/liburing.git small-fixes
for you to fetch changes up to 7039f036302b2f9119a36c55bd5b898bac1ec7e4:
add missing noexcept, local inline, const quals (2025-09-24 15:41:47 -0700)
-------------------------------------------------------------- …
```

[GIT PULL] add missing noexcept, local inline, const quals

---

src/Makefile

Fixes https://github.com/axboe/liburing/issues/1470
----
```
The following changes since commit e951bf0c08c81a2ea0c4b7bca7e4494f2043d367:
man: include common -ENOMEM error for zero copy send (2025-09-22 09:55:44 -0600)
https://github.com/rpereira-dev/liburing master
for you to fetch changes up to b02b4205f480b6fbce2dc773805690b1a617ab8f:
Added query.h to install (2025-09-25 13:27:00 +0000)
Romain Pereira (1):
Added query.h to install
src/Makefile | 2 ++
1 file changed, 2 insertions(+)
```

[GIT PULL] Added query.h to install
